### ISSUE TITLE
ServiceControl stops processing all the time

### ISSUE THREAD

**Issue by miknur** [Particular/ServiceControl#1021]
Currently we have ServiceControl version 1.42.0 installed and it fails to stay up and running.
EventLog contains the following errormessage:
A message import has failed. A log file has been written to C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl\Logs\FailedImports\Error\524983fe-689c-4369-9587-3a6ce6c2cb19.txt

Actual txt-file contains the following error:

Exception:
The given key was not present in the dictionary.
StackTrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ServiceControl.Contracts.Operations.ImportFailedMessage.ParseFailureDetails(Dictionary`2 headers) in C:\Build\src\ServiceControl\Contracts\Operations\ImportFailedMessage.cs:line 31
   at ServiceControl.Contracts.Operations.ImportFailedMessage..ctor(TransportMessage message) in C:\Build\src\ServiceControl\Contracts\Operations\ImportFailedMessage.cs:line 11
   at ServiceControl.Operations.ErrorQueueImport.InnerHandle(TransportMessage message) in C:\Build\src\ServiceControl\Operations\ErrorQueueImport.cs:line 39
   at ServiceControl.Operations.ErrorQueueImport.Handle(TransportMessage message) in C:\Build\src\ServiceControl\Operations\ErrorQueueImport.cs:line 34
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 89
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 344
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 227
Source:
mscorlib
TargetSite:
TValue get_Item(TKey)

**Comment by SzymonPobiega** [comment]
@miknur looking at the stack trace you are definitely not running 1.42.0 but some very old version of ServiceControl dating back to 2016. This issue has most likely been solved since then. Can you upgrade your instance to the latest?

**Comment by miknur** [comment]
Hi
It shows that version 1.42.0 is installed.

![versions](https://user-images.githubusercontent.com/32671138/31384901-a7ef611a-adc9-11e7-93e2-7fc092e362aa.GIF)

**Comment by SzymonPobiega** [comment]
@miknur please open ServiceControl Management Utility. If you SC instance is outdated it should show the upgrade option.

**Comment by miknur** [comment]
Hi
The first errormessage stacktrace was propably taken before we updated SC.
Here is more recent error.
Exception:
The given key was not present in the dictionary.
StackTrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ServiceControl.Operations.FailedMessageFactory.ParseFailureDetails(IReadOnlyDictionary`2 headers) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\FailedMessageFactory.cs:line 39
   at ServiceControl.Operations.ErrorQueueImport.InnerHandle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\ErrorQueueImport.cs:line 138
   at ServiceControl.Operations.ErrorQueueImport.Handle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\ErrorQueueImport.cs:line 81
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 89
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 344
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action(TransactionSettings transactionSettings, TransactionOptions transactionOptions, MsmqUnitOfWork unitOfWork, MessageQueue receiveQueue, MessageQueue errorQueue, CircuitBreaker circuitBreaker, CriticalError criticalError, AutoResetEvent peekResetEvent, TimeSpan receiveTimeout, SemaphoreSlim throttlingSemaphore, Func`2 tryProcessMessage, Action`2 endProcessMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 229
Source:
mscorlib
TargetSite:
TValue get_Item(TKey)

We have updated SC instance also ->
![servicecontrolmanagement](https://user-images.githubusercontent.com/32671138/31385958-ca942af8-adcd-11e7-872e-944cae50e7b6.GIF)

**Comment by SzymonPobiega** [comment]
It seems like the message that is in the `error` queue does not have the `NServiceBus.FailedQ` header. This header is mandatory on all failed messages.

You can check out that message if you switch SC into the [maintenance mode](https://docs.particular.net/servicecontrol/use-ravendb-studio) and RavenDB studio to browse the database in the `FailedErrorImports` collection. There you can extract the actual message.

**Comment by miknur** [comment]
Yes, there is 2600 messages in failedimports atm. FailedQ header is empty on those messages. How can we fix the error ? . Is it safe to delete all messages from failedimports and restart servicecontrol ?

**Comment by SzymonPobiega** [comment]
We should figure out how these messages got there in the first place. Can you open a support case and attach some of the messages there so that we can help you tell where these messages came from? E.g. one of the endpoints might be misconfigured and thus sending audit messages to the error queue.

**Comment by miknur** [comment]
Hi

 

This was indeed the case.  One endpoint is misconfigured.

 

Thanks for your help.

 

Greets, Mika

**Comment by miknur** [comment]
Seems like one of the endpoints is misconfigured. Thanks for your help.

**Comment by SzymonPobiega** [comment]
@miknur No worries. Glad that it worked.
