### ISSUE TITLE
SCMU Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#1087]
Environment is Windows 2012 R2
Version: 1.46.1

I try to drag the Window and then get an exception dialog, interestingly closing it results in the parent window now to be draggable. Same applies to resizing. Error does not always happen as seen in the following screencapture.

![image](https://user-images.githubusercontent.com/152998/35577415-c9f268be-05e1-11e8-8906-aad0a583fa3c.png)

## Exception

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ServiceControl.Config.Xaml.Behaviours.BorderlessWindowBehavior.HwndHook(IntPtr hWnd, Int32 message, IntPtr wParam, IntPtr lParam, Boolean& handled) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl.Config\Xaml\Behaviours\BorderlessWindowBehavior.cs:line 52
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by mikeminutillo** [comment]
Out of interest do you have you multiple monitors? And is your primary on the right?

**Comment by boblangley** [comment]
We triaged this bug.

In an attempt to understand scope and severity we tried to reproduce and were unable to. Based on the exception information this is occurring during an assignment of a new variable to a predefined constant:

https://github.com/Particular/ServiceControl/blob/5c0da64213bb04b82b2fdfa1f62dfe044cb00475/src/ServiceControl.Config/Xaml/Behaviours/BorderlessWindowBehavior.cs#L52

Without a reliable reproduction we are not convinced this can be addressed. We have not have wide-spread reports of this bug from users, so it must be rare indeed. We are going to close this bug, it (or another) issue can be opened if needed in the future.
