### ISSUE TITLE
SCMU not compatible with service accounts, results in System.Exception: Not a valid account

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#1114]
I configured my ServiceControl instance to run under `NT Service\Particular.ServiceControl$SQL` but SCMU then fails to load with a **System.Exception: Not a valid account**

SCMU then quits, you cannot manage any instances.

```
System.Exception: Not a valid account
   at ServiceControlInstaller.Engine.Accounts.UserAccount.ParseAccountName(String accountName) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Accounts\UserAccount.cs:line 125
   at ServiceControlInstaller.Engine.Instances.ServiceControlInstance.DefaultLogPath() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\ServiceControlInstance.cs:line 291
   at ServiceControlInstaller.Engine.Instances.ServiceControlInstance.Reload() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\ServiceControlInstance.cs:line 57
   at ServiceControlInstaller.Engine.Instances.InstanceFinder.<>c.<ServiceControlInstances>b__2_1(WindowsServiceController p) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\Instances.cs:line 33
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ServiceControlInstaller.Engine.Instances.InstanceFinder.ServiceControlInstances() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\Instances.cs:line 33
   at ServiceControlInstaller.Engine.Instances.InstanceFinder.AllInstances() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\Instances.cs:line 50
   at ServiceControl.Config.UI.ListInstances.ListInstancesViewModel.RefreshInstances() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl.Config\UI\ListInstances\ListInstancesViewModel.cs:line 36
```

![image](https://user-images.githubusercontent.com/152998/40043138-e0ccacfe-5823-11e8-96f0-8d48d80075c1.png)

**Comment by mikeminutillo** [comment]
@ramonsmits can you create the instance by using `.\Particular.ServiceControl$SQL`?

This seems to be the section of code https://github.com/Particular/ServiceControl/blob/master/src/ServiceControlInstaller.Engine/Accounts/UserAccount.cs#L102

**Comment by ramonsmits** [comment]
@mikeminutillo I don't know what you are asking. It is already created, I've set that account manually in the windows service settings. When I started SCMU I'm getting this error and SCMU does not show anything. I can only kill it.
