### ISSUE TITLE
Clean install produces raven errors 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceControl#1118]
* version: 1.47.2
 * Windows server 2012 R2

```
2018-04-04 11:45:48.1671|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1671|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1842|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1842|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1842|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1981|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1981|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1981|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.1981|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.2181|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.2181|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.2181|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.2331|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:48.2331|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Api.JetBeginSession(JET_INSTANCE instance, JET_SESID& sesid, String username, String password) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 822
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\General.cs:line 76
2018-04-04 11:45:54.1091|10|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index QueueAddressIndex. Trying to recover index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:54.1091|5|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index FailureGroupsViewIndex. Trying to recover index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:54.1091|9|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index RetryBatches/ByStatus/ReduceInitialBatchSize. Trying to recover index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:54.6883|9|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index RetryBatches/ByStatus/ReduceInitialBatchSize. Recovery operation failed, forcibly resetting index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:54.6883|10|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index QueueAddressIndex. Recovery operation failed, forcibly resetting index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:54.6883|5|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index FailureGroupsViewIndex. Recovery operation failed, forcibly resetting index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:55.0152|14|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index SagaDetailsIndex. Trying to recover index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:55.0421|9|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index SagaListIndex. Trying to recover index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:55.1221|9|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index SagaListIndex. Recovery operation failed, forcibly resetting index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
2018-04-04 11:45:55.1221|14|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index SagaDetailsIndex. Recovery operation failed, forcibly resetting index
System.InvalidOperationException: Map-Reduce index corruption detected.
   at Raven.Database.Indexing.IndexStorage.CheckMapReduceIndexState(IDictionary`2 commitData, Boolean resetTried) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 250
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexStorage.cs:line 141
```

**Comment by SzymonPobiega** [comment]
Thanks. I can reproduce it on my machine. We'll investigate.
