### ISSUE TITLE
Sending a raw message, that fails, results in SC not being able to return the failed message to SP

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceControl#1119]
So here https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/MessageFailures/Api/GetErrorById.cs#L55

It is assumed that many headers exist and no defensive code is done

When sending a raw message using this approach https://docs.particular.net/transports/sql/operations-scripting#native-send-the-native-send-helper-methods-in-c

The only required header for NSB endpoints to successfully process a message is `NServiceBus.EnclosedMessageTypes`. But, if the message processing fails, this results in `processingAttempt.MessageMetadata` in SC missing the `SendingEndpoint` and `TimeSent` headers.

When SP queries for this failed message SC throws a `KeyNotFoundException`

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ServiceControl.MessageFailures.Api.GetErrorById.Map(FailedMessage message, IAsyncDocumentSession session) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\MessageFailures\Api\GetErrorById.cs:line 55
   at ServiceControl.MessageFailures.Api.GetErrorById.<<-ctor>b__0_1>d.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\MessageFailures\Api\GetErrorById.cs:line 44
```

**Comment by SimonCropp** [comment]
for the next person who finds this. the min headers when sending, to make it work in SC, are:

 * `NServiceBus.EnclosedMessageTypes`
 * `NServiceBus.OriginatingMachine`
 * `NServiceBus.OriginatingEndpoint`
 * `NServiceBus.TimeSent`

**Comment by SimonCropp** [comment]
> As far as I can see SP has problems displaying the message but is still able to retry it correctly and other failed messages are not affected.

correct. but it is difficult to determine if a retry is safe when you cant view the exception details
