### ISSUE TITLE
Cannot ingest message with missing Intent on ASB

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#1219]
When running on Azure Service Bus, ServiceControl cannot ingest any messages which are missing the Intent property. This is caused by https://github.com/Particular/NServiceBus.AzureServiceBus/issues/718

ServiceControl shuts down with the following error in the log file

```
2018-06-11 09:08:21.4662|14|Warn|NServiceBus.CircuitBreakers.RepeatedFailuresOverTimeCircuitBreaker|The circuit breaker for AzureServiceBusDequeueStrategy will now be triggered
2018-06-11 09:08:21.4662|14|Fatal|NServiceBus|Failed to receive message from Azure ServiceBus.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.BrokeredMessageConverter.ToTransportMessage(BrokeredMessage message) in C:\BuildAgent\work\7eae8ccbde2584d7\src\Transport\Utils\BrokeredMessageConverter.cs:line 24
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusDequeueStrategy.TryProcessMessage(Object obj) in C:\BuildAgent\work\7eae8ccbde2584d7\src\Transport\Receiving\AzureServiceBusDequeueStrategy.cs:line 125
   at System.Threading.Tasks.Task.Execute()
```

**Comment by danielmarbach** [comment]
6.4.3 is released https://github.com/Particular/NServiceBus.AzureServiceBus/releases/tag/6.4.3
