### ISSUE TITLE
SC Log is spammed with error: Unhandled exception in Metrics.NET Library Error reading performance counter data. 

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#1375]
SC instance is running with a windows service account. During startup it tries to register various performance counters based on the DEBUG log entries:

The first 3 items shown in the log:
```
2018-08-22 10:48:50.5768|5|Debug|Metrics.PerfCounters.PerformanceCounters|Registering performance counter [Available MBytes] in category [Memory] for instance [none]
...
2018-08-22 10:48:50.6107|5|Debug|Metrics.PerfCounters.PerformanceCounters|Registering performance counter [Free System Page Table Entries] in category [Memory] for instance [none]
...
2018-08-22 10:48:50.6237|5|Debug|Metrics.PerfCounters.PerformanceCounters|Registering performance counter [Pages Input/sec] in category [Memory] for instance [none]
```

They all result in the following error:

```
2018-08-22 10:48:50.6367|5|Error|Metrics.MetricsErrorHandler|Metrics: Unhandled exception in Metrics.NET Library Error reading performance counter data. The application is currently running as user NT SERVICE\Particular.ServiceControl$SQL. Make sure the user has access to the performance counters. The user needs to be either Admin or belong to Performance Monitor user group. Access to the registry key 'Global' is denied.
System.UnauthorizedAccessException: Access to the registry key 'Global' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalGetValue(String name, Object defaultValue, Boolean doNotExpand, Boolean checkSecurity)
   at Microsoft.Win32.RegistryKey.GetValue(String name)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName)
   at Metrics.PerfCounters.PerformanceCounters.WrappedRegister(MetricsContext context, String name, Unit unit, String category, String counter, String instance, Func`2 derivate, MetricTags tags)
   at Metrics.PerfCounters.PerformanceCounters.Register(MetricsContext context, String name, Unit unit, String category, String counter, String instance, Func`2 derivate, MetricTags tags)
```

After that the instance seems to run fine.

**Comment by ramonsmits** [comment]
Resolved this by adding the service account to the suggested user group:

![2018-08-22_11-08-43](https://user-images.githubusercontent.com/152998/44454448-df81cc00-a5fb-11e8-8fea-6b1b084f787c.gif)

**Comment by ramonsmits** [comment]
Is SCMU or SC during setup adding that account to that user group? I might have this situation with this SC instance because of https://github.com/Particular/ServiceControl/issues/1114

**Comment by tamararivera** [comment]
Closing this, as this is [documented](https://docs.particular.net/servicecontrol/configure-non-privileged-service-account#performance-counters) in our docs.
