### ISSUE TITLE
Cannot configure forwarding queues

### ISSUE THREAD

**Issue by ufonator** [Particular/ServiceControl#1403]
Hi,

I'm getting an error during installation of ServiceControl (v3.1.1, RabbitMQ v 3.7.7). I'm trying to configure audit.log/error.log forwarding queues but service cant start. Any advice?

this is log from cmd:

Unhandled Exception: RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=404, text=**"NOT_FOUND - no exchange 'Particular.ServiceControl' in vhost '/'",** classId=40, methodId=30, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_ExchangeBind(String destination, String source, String routingKey, Boolean nowait, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.AutorecoveringModel.ExchangeBind(String destination, String source, String routingKey, IDictionary`2 arguments)
   at NServiceBus.Transport.RabbitMQ.ConventionalRoutingTopology.SetupSubscription(IModel channel, Type type, String subscriberName)
   at NServiceBus.Transport.RabbitMQ.SubscriptionManager.Subscribe(Type eventType, ContextBag context)
   at NServiceBus.EnforceSubscribeBestPracticesBehavior.Invoke(ISubscribeContext context, Func`2 next)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at NServiceBus.Features.FeatureStartupTaskController.Start(IBuilder builder, IMessageSession messageSession)
   at NServiceBus.Features.FeatureActivator.<StartFeatures>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<StartFeatures>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceBus.Management.Infrastructure.NServiceBusFactory.<CreateAndStart>d__2.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\NServiceBusFactory.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Particular.ServiceControl.Bootstrapper.<Start>d__10.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Bootstrapper.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Particular.ServiceControl.Commands.ImportFailedAuditsCommand.RunAndWait(HostArguments args) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Hosting\Commands\ImportFailedAuditsCommand.cs:line 33
   at Particular.ServiceControl.Commands.CommandRunner.Execute(HostArguments args) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Hosting\Commands\CommandRunner.cs:line 16
   at Particular.ServiceControl.Program.Main(String[] args) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Program.cs:line 28

this is log from eventlog:

Service cannot be started. System.Exception: Unable to write to forwarding queue audit.log ---> System.Exception: **Message could not be routed to audit.log: 312 NO_ROUTE**
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Operations.MessageForwarder.<VerifyCanReachForwardingAddress>d__2.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\MessageForwarder.cs:line 58
   --- End of inner exception stack trace ---
   at ServiceControl.Operations.MessageForwarder.<VerifyCanReachForwardingAddress>d__2.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\MessageForwarder.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus...

**Comment by mikeminutillo** [comment]
Hi @ufonator 

It looks like ServiceControl has not created any of it's queues. How are you installing this instance? Using the ServiceControl Management Utility?

**Comment by ufonator** [comment]
Hi @mikeminutillo 

Yes i was trying to intall and configure ServiceControl thru ServiceControl Management Utility. I'm able to install ServiceControl without forwarding queues but after i configure forwarding queues audit.log error.log, service cannot start (error occured i found it in event log). Then i tried to run service thru command line and same error ocurred too (that first error i wrote before in post.)

**Comment by mikeminutillo** [comment]
Thanks @ufonator. It looks like it might be a bug. ServiceControl is not creating the audit log queue. I am checking with the RabbitMQ team.

In the meantime, if you create an `audit.log` queue in your Rabbit broker by hand, ServiceControl should be able to start.

**Comment by ufonator** [comment]
Hi @mikeminutillo 

Problem is...even when i created audit and error log queue by hand ServiceControl fires same error. I prepared you this [https://www.dropbox.com/s/yzx089dqd5acjm7/2018-09-11_08-27-53.MP4?dl=0](video). Am i doing something wrong?

**Comment by mikeminutillo** [comment]
@ufonator I believe that you need to create an exchange (with the same name) and bind it to the queue. There is [a helper method](https://docs.particular.net/transports/rabbitmq/operations-scripting#create-queues) in our RabbitMQ documentation to help. Normally ServiceControl would do that for you.

**Comment by WilliamBZA** [comment]
Fixed by #1408 

Closing for now, a release will be out shortly
