### ISSUE TITLE
Service control fails to start after installation (v.3.1.1) 

### ISSUE THREAD

**Issue by fredricadell** [Particular/ServiceControl#1416]
On a new server (Windows 2016) with MSMQ setup and activated and writing to D:\MSMQ instead of default. 
ServiceControl is installed with defaults and a new instance created with defaults and msmq as transport Local System as running user. 

When starting the instance for the first time it fails whith this message : 
```
Service cannot be started. System.Exception: Failed to send message to address: Particular.ServiceControl@BUSTST1 ---> System.Messaging.MessageQueueException: Insufficient resources to perform operation.
   at System.Messaging.MessageQueue.SendInternal(Object obj, MessageQueueTransaction internalTransaction, MessageQueueTransactionType transactionType)
   at System.Messaging.MessageQueue.Send(Object obj, String label, MessageQueueTransactionType transactionType)
   at NServiceBus.Transport.Msmq.MsmqMessageDispatcher.ExecuteTransportOperation(TransportTransaction transaction, UnicastTransportOperation transportOperation)
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.Msmq.MsmqMessageDispatcher.ThrowFailedToSendException(String address, Exception ex)
   at NServiceBus.Transport.Msmq.MsmqMessageDispatcher.ExecuteTransportOperation(TransportTransaction transaction, UnicastTransportOperation transportOperation)
   at NServiceBus.Transport.Msmq.MsmqMessageDispatcher.Dispatch(TransportOperations outgoingMe...

```
We´ve checked with sysmon for access rights and no trace of that any error of access rights are shown.

**Comment by WilliamBZA** [comment]
[Here](https://support.microsoft.com/en-au/help/899612/how-to-set-up-computer-quotas-and-queue-quotas-in-microsoft-message-qu) is a link on how to tweak the message queue quotas

**Comment by fredricadell** [comment]
Hi @WilliamBZA  , we have the following machineQouta : 3048576. I cbanged that again to 50000000 kb (5 gb) and restarted the MSMQ service with the same result.. Im starting to think there might be a access right problem to the disk because the disc itself has 90 gb free space. This is a clean new server so no messages has ever been sent to or from the server, Only the one message from ServiceControl itself.

**Comment by andreasohlund** [comment]
What's the name of the new machine?

Is it longer than 15 characters?

https://stackoverflow.com/a/1732531

**Comment by fredricadell** [comment]
No .. after reinstalling MSMQ service role on server it started working.. must have been some glitch from the provider of the machine (Virtual)  so closing this issue.. Thank you for the rapid response!!
