### ISSUE TITLE
Incorrect headers added to messages when retried

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#1618]
## Who's affected

All customer retrying messages originating from non-NServiceBus endpoints and relies on the message intent or message durability headers for custom logic.

## Symptoms

The retried message will incorrectly contain the `NServiceBus.MessageIntent` and `NServiceBus.NonDurableMessage` headers.

## Analysis

As part of investigating a support case for a MSMQ user (not confirmed this on any other transport yet) I can see the following headers being present on the retried messages that is comming from native integration (ie no headers are present on the original message):

```
// This is the one that is causing grief for the customer since they have logic depending on the intent 
<HeaderInfo>
    <Key>NServiceBus.MessageIntent</Key>
    <Value>0</Value>
  </HeaderInfo>
//this one feels dangerous since the message was coming in to the endpoint as durable
  <HeaderInfo>
    <Key>NServiceBus.NonDurableMessage</Key>
    <Value>True</Value>
  </HeaderInfo>

// The following ones should be harmless but should be removed
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.InnerExceptionType</Key>
    <Value>System.Exception</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.HelpLink</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Message</Key>
    <Value>An error occurred while attempting to extract logical messages from incoming physical message 72802d3f-fa83-4088-8d02-8489a341c6e2\23577</Value>
  </HeaderInfo>

// These ones seems incorrect given that you can route retries to other endpoint this can be confusing
  <HeaderInfo>
    <Key>NServiceBus.ProcessingMachine</Key>
    <Value>CARBONX1</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ProcessingEndpoint</Key>
    <Value>Samples.Msmq.Simple</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostid</Key>
    <Value>8940a2f013379fe55dcf6565929de361</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostdisplayname</Key>
    <Value>CARBONX1</Value>
  </HeaderInfo>
```

### Use case that is causing issues

The customer has a message mutator that checks for the absence of the `NServiceBus.MessageIntent` header to detect and preprocess incoming integration messages. Since that header is now incorrectly present after retrying via SC that mutator no longer fires and message fails to be processed due to that.

### Details

Original message had no headers at all

#### Headers when present in error q

<details>
<?xml version="1.0"?>
<ArrayOfHeaderInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <HeaderInfo>
    <Key>NServiceBus.CorrelationId</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.MessageId</Key>
    <Value>72802d3f-fa83-4088-8d02-8489a341c6e2\23577</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.ExceptionType</Key>
    <Value>NServiceBus.MessageDeserializationException</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.InnerExceptionType</Key>
    <Value>System.Exception</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.HelpLink</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Message</Key>
    <Value>An error occurred while attempting to extract logical messages from incoming physical message 72802d3f-fa83-4088-8d02-8489a341c6e2\23577</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Source</Key>
    <Value>NServiceBus.Core</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.StackTrace</Key>
    <Value>NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message 72802d3f-fa83-4088-8d02-8489a341c6e2\23577 ---&gt; System.Exception: Could not determine type for node: 'test'.
   at NServiceBus.XmlDeserialization.InferNodeType(XmlNode node, Object parent)
   at NServiceBus.XmlDeserialization.Process(XmlNode node, Object parent, Type nodeType)
   at NServiceBus.XmlDeserialization.Deserialize(Stream stream, IList`1 messageTypesToDeserialize)
   at NServiceBus.DeserializeLogicalMessagesConnector.Extract(IncomingMessage physicalMessage)
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   --- End of inner exception stack trace ---
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   at NServiceBus.DeserializeLogicalMessagesConnector.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SubscriptionReceiverBehavior.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.&lt;Invoke&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.Msmq.ReceiveStrategy.&lt;TryProcessMessage&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.Msmq.SendsAtomicWithReceiveNativeTransactionStrategy.&lt;ProcessMessage&gt;d__2.MoveNext()</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.TimeOfFailure</Key>
    <Value>2019-04-11 08:58:26:401609 Z</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.FailedQ</Key>
    <Value>Samples.Msmq.Simple@CARBONX1</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ProcessingMachine</Key>
    <Value>CARBONX1</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ProcessingEndpoint</Key>
    <Value>Samples.Msmq.Simple</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostid</Key>
    <Value>8940a2f013379fe55dcf6565929de361</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostdisplayname</Key>
    <Value>CARBONX1</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>CorrId</Key>
    <Value />
  </HeaderInfo>
</ArrayOfHeaderInfo>
</details>

#### Headers when back in the endpoint queue

<details>
<?xml version="1.0"?>
<ArrayOfHeaderInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <HeaderInfo>
    <Key>NServiceBus.CorrelationId</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.MessageId</Key>
    <Value>72802d3f-fa83-4088-8d02-8489a341c6e2\23577</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.ExceptionType</Key>
    <Value>NServiceBus.MessageDeserializationException</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.InnerExceptionType</Key>
    <Value>System.Exception</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.HelpLink</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Message</Key>
    <Value>An error occurred while attempting to extract logical messages from incoming physical message 72802d3f-fa83-4088-8d02-8489a341c6e2\23577</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Source</Key>
    <Value>NServiceBus.Core</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.StackTrace</Key>
    <Value>NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message 72802d3f-fa83-4088-8d02-8489a341c6e2\23577 ---&gt; System.Exception: Could not determine type for node: 'test'.
   at NServiceBus.XmlDeserialization.InferNodeType(XmlNode node, Object parent)
   at NServiceBus.XmlDeserialization.Process(XmlNode node, Object parent, Type nodeType)
   at NServiceBus.XmlDeserialization.Deserialize(Stream stream, IList`1 messageTypesToDeserialize)
   at NServiceBus.DeserializeLogicalMessagesConnector.Extract(IncomingMessage physicalMessage)
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   --- End of inner exception stack trace ---
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   at NServiceBus.DeserializeLogicalMessagesConnector.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SubscriptionReceiverBehavior.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.&lt;Invoke&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.&lt;Invoke&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.Msmq.ReceiveStrategy.&lt;TryProcessMessage&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.Msmq.SendsAtomicWithReceiveNativeTransactionStrategy.&lt;ProcessMessage&gt;d__2.MoveNext()</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.TimeOfFailure</Key>
    <Value>2019-04-11 08:58:26:401609 Z</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.FailedQ</Key>
    <Value>Samples.Msmq.Simple@CARBONX1</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ProcessingMachine</Key>
    <Value>CARBONX1</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ProcessingEndpoint</Key>
    <Value>Samples.Msmq.Simple</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostid</Key>
    <Value>8940a2f013379fe55dcf6565929de361</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostdisplayname</Key>
    <Value>CARBONX1</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>CorrId</Key>
    <Value />
  </HeaderInfo>
</ArrayOfHeaderInfo>
</details>

### ServiceControl MessageIntent behaviors

When ServiceControl stages the message it assigns the [intent stored in the `ProcessingAttempt`](https://github.com/Particular/ServiceControl/blob/575f2a8cb4b9b2d6b17b2170d29a558004d7a1e1/src/ServiceControl/MessageFailures/FailedMessage.cs#L47):

https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Recoverability/Retrying/RetryProcessor.cs#L312

```
            var transportMessage = new OutgoingMessage(message.Id, headersToRetryWith, emptyBody);
            transportMessage.Headers[Headers.MessageIntent] = attempt.MessageIntent.ToString();
            if (attempt.Recoverable)
            {
                transportMessage.Headers[Headers.NonDurableMessage] = true.ToString();
            }

            if (attempt.CorrelationId != null)
            {
                transportMessage.Headers[Headers.CorrelationId] = attempt.CorrelationId;
            }

            return sender.Dispatch(new TransportOperations(new TransportOperation(transportMessage, new UnicastAddressTag(returnToSender.InputAddress))), transaction, contextBag);
```

When importing a failed message ServiceControl assigns a message intent if none was present:

https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Infrastructure/TransportMessageExtensions.cs#L62-L72

https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Operations/ErrorPersister.cs#L76

**Comment by boblangley** [comment]
I updated the description with lines in ServiceControl where we record or re-introduce message intent. The `RetryProcessor` should not set the header if it wasn't present in the headers dictionary. Setting the message intent is as old as ServiceControl, which means either:

We used to require it to dispatch messages in v5

or more likely:

This is just another example of ServiceControl assuming it is processing messages generated by NServiceBus.

**Comment by andreasohlund** [comment]
After this fix no extra headers is added by SC and the message returned to the queue have the following headers set:


```
<ArrayOfHeaderInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <HeaderInfo>
    <Key>NServiceBus.CorrelationId</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.MessageId</Key>
    <Value>72802d3f-fa83-4088-8d02-8489a341c6e2\25777</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>CorrId</Key>
    <Value />
  </HeaderInfo>
  <HeaderInfo>
    <Key>ServiceControl.Retry.UniqueMessageId</Key>
    <Value>dd380241-051a-1dd4-9a35-4192f28919a1</Value>
  </HeaderInfo>
</ArrayOfHeaderInfo>
```
