### ISSUE TITLE
Adding MSMQ ServiceControl instance fails with Raven Client Error

### ISSUE THREAD

**Issue by eleg8r** [Particular/ServiceControl#1642]
Can you please let me know what could be an issue with adding a ServiceControl MSMQ instance (on Windows Server 2016 Standard) in ServiceControl Management (Trial expiry date: 6/5/2019). Here are the details:

1) I installed Particular.ServiceControl-3.7.2.exe and 

2) Then ran these commands:

Import-Module NServiceBus.PowerShell
Install-NServiceBusDTC
Install-NServiceBusMSMQ
(all ran successfully confirming the correct setup of the services)

3) Then I confirmed that I have .NET Framework 4.6.2 or higher:
Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\' | Get-ItemPropertyValue -Name Release | Foreach-Object { $_ -ge 394802 }

4) **But when adding a ServiceControl instance for MSMQ transport ServiceControl showed this error** 

Issues adding instance serviceControl ServiceControl.exe threw an error when creating queues this Tipically indicates a configuration error. The error output from Servicecontrol.exe was Unhandled Exception: Raven.Abstractions.Exceptions.TransformComilationException: Exception has been thrown by the target of an invocatin at Raven.Client.Connection.Async.AsyncServerClient.<DirectPutTransformerAsync>d_47.MoveNext() --- End of stack trace from previous locatin where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Raven.Client.Connection.ReplicationInformerBase`1<

5) **Looking at the event viewer I see 2 errors logged there:**

**- .NET Runtime:**
Application: ServiceControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Raven.Abstractions.Exceptions.TransformCompilationException
   at Raven.Client.Connection.Async.AsyncServerClient+<DirectPutTransformerAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Raven.Client.Connection.ReplicationInformerBase`1+<TryOperationAsync>d__34`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Raven.Client.Connection.ReplicationInformerBase`1+<ExecuteWithReplicationAsync>d__33`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Raven.Client.Connection.Async.AsyncServerClient+<ExecuteWithReplication>d__173`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Raven.Abstractions.Util.AsyncHelpers+<>c__DisplayClass1_1`1+<<RunSync>b__0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Raven.Abstractions.Util.AsyncHelpers.RunSync[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task`1<System.__Canon>>)
   at Raven.Client.Indexes.AbstractTransformerCreationTask.Execute(Raven.Client.Connection.IDatabaseCommands, Raven.Client.Document.DocumentConvention)
   at Raven.Client.Indexes.IndexCreation.CreateTransformers(System.ComponentModel.Composition.Hosting.ExportProvider, Raven.Client.IDocumentStore)
   at Raven.Client.Indexes.IndexCreation.CreateIndexes(System.ComponentModel.Composition.Hosting.ExportProvider, Raven.Client.IDocumentStore)
   at ServiceControl.Infrastructure.RavenDB.RavenBootstrapper.StartRaven(Raven.Client.Embedded.EmbeddableDocumentStore, ServiceBus.Management.Infrastructure.Settings.Settings, ServiceControl.Infrastructure.MarkerFileService, Boolean)
   at ServiceControl.Infrastructure.RavenDB.RavenBootstrapper.Customize(NServiceBus.EndpointConfiguration)
   at NServiceBus.EndpointConfiguration.ForAllTypes[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.Type>, System.Action`1<System.Type>)
   at NServiceBus.EndpointConfiguration.Build()
   at NServiceBus.Endpoint.Create(NServiceBus.EndpointConfiguration)
   at ServiceBus.Management.Infrastructure.NServiceBusFactory.Create(ServiceBus.Management.Infrastructure.Settings.Settings, ServiceControl.Transports.TransportCustomization, ServiceControl.Transports.TransportSettings, ServiceBus.Management.Infrastructure.Settings.LoggingSettings, Autofac.IContainer, System.Action`1<NServiceBus.ICriticalErrorContext>, Raven.Client.Embedded.EmbeddableDocumentStore, NServiceBus.EndpointConfiguration, Boolean)
   at Particular.ServiceControl.SetupBootstrapper+<Run>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Particular.ServiceControl.Commands.SetupCommand+<Execute>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Particular.ServiceControl.Commands.CommandRunner+<Execute>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Particular.ServiceControl.Program+<Main>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Particular.ServiceControl.Program.<Main>(System.String[])

**- And also Application Error:**

Faulting application name: ServiceControl.exe, version: 3.7.2.0, time stamp: 0xc2705a0d
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2848, time stamp: 0x5c7f626e
Exception code: 0xe0434352
Fault offset: 0x0000000000034078
Faulting process id: 0x59c
Faulting application start time: 0x01d507401f669ec4
Faulting application path: C:\Program Files (x86)\Particular Software\Particular.ServiceControl\ServiceControl.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: fd613d72-c46c-4aeb-993c-7be4dfbf5550
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mikeminutillo** [comment]
It looks like ServiceControl is having trouble setting up it's internal database. Can you check the database folder and see if anything got created there? 

Are you using the ServiceControl Management Utlity to create the instance or the powershell script?

**Comment by mikeminutillo** [comment]
Hey @eleg8r, just checking in to see if you've had any luck setting up this ServiceControl instance.
