### ISSUE TITLE
Nservicebus not taking message from rabbitMq queue after reestablished connection

### ISSUE THREAD

**Issue by szymo0** [Particular/ServiceControl#1713]
Hi,

I have problem with reciving message from queue. After some problem with connection i get information that rabbitMq connection reestablished. Problem is that message aren't recive from queue after this situation. I past log from my app:

`2019-07-10 02:01:13.216 INFO  NServiceBus.Transport.RabbitMQ.ChannelProvider Connection to the broker reestablished successfully.
2019-07-10 02:01:28.163 WARN  RabbitMQ.Client.IConnection 'Publish' connection shutdown: AMQP close-reason, initiated by Library, code=541, text="Unexpected Exception", classId=0, methodId=0, cause=System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(NetworkBinaryReader reader)
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
2019-07-10 02:01:28.163 INFO  NServiceBus.Transport.RabbitMQ.ChannelProvider Attempting to reconnect in 10 seconds.
2019-07-10 02:04:30.037 INFO  NServiceBus.Transport.RabbitMQ.ChannelProvider Reconnecting to the broker failed.
RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at RabbitMQ.Client.Impl.SocketFrameHandler.Write(Byte[] buffer)
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.ProtocolBase.CreateConnection(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at NServiceBus.Transport.RabbitMQ.ConnectionFactory.CreateConnection(String connectionName, Boolean automaticRecoveryEnabled)
   at NServiceBus.Transport.RabbitMQ.ChannelProvider.CreateConnection()
   at NServiceBus.Transport.RabbitMQ.ChannelProvider.Reconnect()
2019-07-10 02:04:30.037 INFO  NServiceBus.Transport.RabbitMQ.ChannelProvider Attempting to reconnect in 10 seconds.
2019-07-10 02:04:40.607 INFO  NServiceBus.Transport.RabbitMQ.ChannelProvider Connection to the broker reestablished successfully.`

there are no message in log after :"Connection to the broker reestablished successfully.".

My question is: Can I check state of NServicebus connection, to recreate endpoint manualy? Or can you give me some advice how to mange this situation. In my enviroment connection problem could occured from time to time. 

Second question is: if connection is reestablished, should endpoint should recived message from queue?

I will be greatful from any help in this matter

Regards
Szymek

**Comment by indualagarsamy** [comment]
Hi @szymo0 - since we have a support case on this and also since this is not related to service control specifically, I am going to close this issue. We'll continue on the support case. Thanks.

**Comment by wwaniek5** [comment]
Hi
@indualagarsamy do you have a link to this support case? I can't find it anywhere. I'm observing exactly the same issue (RabbitMQ 3.9.11 and NServiceBus 7.6.0)
Thanks
