### ISSUE TITLE
Cannot upgrade Audit Instance in ServiceControl Management using the Upgrade link

### ISSUE THREAD

**Issue by mohlerm** [Particular/ServiceControl#1737]
Hi

I just upgraded to ServiceControl 4.1.0.
Upgrading the ServiceControl Instance went through but I do not seem to be able to upgrade the Audit instance. It shows the 'Upgrade' button but clicking on it shows no reaction:
![2019-08-16_164515](https://user-images.githubusercontent.com/3135878/63176019-6ddd3200-c045-11e9-8f78-194689c88b4e.png)

I've also tried shutting down the Audit instance prior to updating but didn't help.

However, using the powershell command:
`Invoke-ServiceControlAuditInstanceUpgrade -Name Particular.ServiceControl.Audit`
upgrade seems to have worked (version number is updated in the UI).

However I'm seeing the following errors in my ServiceControl instance log:
```
2019-08-16 16:48:42.1917|46|Warn|ServiceControl.CompositeViews.Messages.ScatterGatherApi`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Collections.Generic.IList`1[[ServiceControl.CompositeViews.Messages.MessagesView, ServiceControl, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]|Failed to query remote instance at http://removed/api/.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at ServiceControl.CompositeViews.Messages.ScatterGatherApi`2.<ParseResult>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.CompositeViews.Messages.ScatterGatherApi`2.<FetchAndParse>d__19.MoveNext()
```

I was able to get rid of this message by removing/adding my ServiceControl & ServiceControl.Audit instance.

Cheers

**Comment by WilliamBZA** [comment]
Definitely a bug. Thanks for reporting it, I'll keep you posted

**Comment by SzymonPobiega** [comment]
Workarounds:
- Use `Invoke-ServiceControlAuditInstanceUpgrade -Name Particular.ServiceControl.Audit` as @mohlerm suggested
- Remove existing instance (while preserving logs and data folders) and create a new instance with the same log and data paths

**Comment by danielmarbach** [comment]
Fixed. Closing. Will post the announcement link containing more details soon

**Comment by danielmarbach** [comment]
More details can be found in the announcement https://discuss.particular.net/t/servicecontrol-4-3-1-patch-release-available/1369

**Comment by indualagarsamy** [comment]
Here's the associated PR with the fix: https://github.com/Particular/ServiceControl/pull/1757
