### ISSUE TITLE
If queues do not exist, SC.Monitoring must be reinstalled to recreated the queues

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#1748]
SC.Monitoring does not start after the queue was not present anymore. In my case because I reinstalled MSMQ. I had to reinstall SC.Monitoring for it to recreate all relevant queues.

It would be nice if the installers could be rerun.

```
2017-12-12 22:00:03.9614|4|Fatal|NServiceBus.StartableEndpoint|Receiver Main failed to initialize.
System.InvalidOperationException: There is a problem with the input inputQueue: FormatName:DIRECT=OS:ZOLDER\private$\Particular.Monitoring. See the enclosed exception for details. ---> System.Messaging.MessageQueueException: The queue does not exist or you do not have sufficient permissions to perform the operation.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.MessagePump.QueueIsTransactional()
   --- End of inner exception stack trace ---
   at NServiceBus.MessagePump.QueueIsTransactional()
   at NServiceBus.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings)
   at NServiceBus.TransportReceiver.Init()
   at NServiceBus.StartableEndpoint.<InitializeReceivers>d__3.MoveNext()
```

## Workaround

Run the executable from an elevated (admin) command prompt with the `-s` (setup) and `--serviceName` arguments:

    ServiceControl.exe -s --serviceName=Particular.ServiceControl.Audit.Acceptance
	ServiceControl.Audit.exe -s --serviceName=Particular.ServiceControl.Audit.Acceptance
    ServiceControl.Monitoring.exe -s --serviceName=Particular.Monitoring.Acceptance

**Comment by robbaman** [comment]
Is there any update on this? Especially for testing an acceptance environments this is quite a hassle. We do want monitoring, but we also want to be able to clear the entire RabbitMQ instance. Now we have to use the less-than-optimal UI to recreate the monitoring and auditing instances which involves a bunch of error-prone copy pasting.

It could just create everything on startup like regular endpoints do as well.

**Comment by ramonsmits** [comment]
@robbaman there is a workaroundby running the exe from the commandline as admin with the `-s` argument

**Comment by robbaman** [comment]
I tried that, but I started with the Monitoring executable which did indeed create the queues, but it used the default name `Particular.Monitoring` which we changed to `Particular.Monitoring.Acceptance` because we run all the instances on the same machine for out test/acceptance monitoring.

**Comment by ramonsmits** [comment]
@robbaman In order to use the right queue it needs the `--serviceName` argument:

    -s --serviceName=Particular.Monitoring.Acceptance
    
Added that to the issue description.

**Comment by robbaman** [comment]
I tried that too, but then it seems it actually wants to reinstall the service which gave me new error messages since the service already exists (I assume)

I must admit that after this I just gave up and once again manually removed and installed the service to get the queues. created again. One of these days I'm going to make some time to look into the Powershell module to automate the creation and removal of the SC instance.

If just recreating the queues at startup proves to be too difficult to implement, perhaps a 'export this configuration as Powershell script'-feature would also be welcome.

**Comment by ramonsmits** [comment]
> perhaps a 'export this configuration as Powershell script'-feature would also be welcome.

That actually isn't a bad idea! Created an issue for it:

- https://github.com/Particular/ServiceControl/issues/3705
