### ISSUE TITLE
Audit instance 4.12.0 not processing msgs

### ISSUE THREAD

**Issue by 3komma14** [Particular/ServiceControl#2127]
After upgrading to the latest ServiceControl 4.12.0 the Audit instance have been using a lot of CPU and not picking work from the audit queue. Also not able to stop the service normally. Restarting seem to solve the isse for a short time. 

ravenlog:
```
2020-08-24 07:39:40.2966|11|Warn|Raven.Database.Prefetching.PrefetchingBehavior|WASTE: Discarding future work item without using it, to reduce memory usage
2020-08-24 07:43:19.6514|16|Warn|Raven.Database.Prefetching.PrefetchingBehavior|WASTE: Discarding future work item without using it, to reduce memory usage
2020-08-24 07:43:29.6345|32|Warn|Raven.Client.Connection.Async.AsyncServerClient|Was unable to fetch topology from primary node http://localhost also there is no cached topology
2020-08-24 07:48:55.1127|29|Error|Raven.Client.Changes.RemoteChangesClientBase`3|Got error from server connection for http://localhost on id 1/5fuIbjfKAm4/4BeC78pldtd
System.TimeoutException: Over 45 seconds have passed since we got a server heartbeat, even though we should get one every 10 seconds or so.
This connection is now presumed dead, and will attempt reconnection
2020-08-24 07:48:55.1127|32|Error|Raven.Client.Changes.RemoteChangesClientBase`3|Got error from server connection for http://localhost on id 1/5fuIbjfKAm4/4BeC78pldtd
System.AggregateException: One or more errors occurred. ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Raven.Client.Connection.ObservableLineStream.<Start>b__8_0(Task`1 task)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Raven.Client.Connection.ObservableLineStream.<Start>b__8_0(Task`1 task)
   at System.Threading.Tasks.Task.Execute()<---
```

logfile:
```
2020-08-24 07:49:55.1646|34|Warn|NServiceBus.CustomChecks.TimerBasedPeriodicCheck|Failed to report periodic check to ServiceControl.
Microsoft.Azure.ServiceBus.ServiceBusTimeoutException: The operation did not complete within the allocated time 00:01:00 for object message. ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object message.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__58.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by WilliamBZA** [comment]
@3komma14 Can you send us the full servicecontrol logfile since upgrading to 4.12.0 to our support mail?

**Comment by 3komma14** [comment]
@WilliamBZA Logs are sent

**Comment by TraGicCode** [comment]
Hey @WilliamBZA ,

Is this something isolated to @3komma14?

**Comment by WilliamBZA** [comment]
At the moment that's the current theory @TraGicCode. Are you also seeing `ServiceBusTimeoutException` exceptions in your logs?

**Comment by TraGicCode** [comment]
Hey @WilliamBZA ,

We are not experiencing this problem but we are planning on upgrading when a release is cut for #2142

**Comment by 3komma14** [comment]
I am closing this issue for now. After scaling up the VM's we have not seen the same issue as described.
