### ISSUE TITLE
Re-importing audit messages fails is audit forwarding is enabled

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#2143]
Re-importing audit messages that failed to be imported during the initial attempt (and are stored in the SC database) fails. 

### Symptoms

Error similar to this one

```
2020-09-04 13:56:36.0861|36|Error|ServiceControl.Audit.Auditing.ImportFailedAudits|Error while attempting to re-import failed audit message cb87301a-bd71-4784-8841-ac2c00c32944.
System.ArgumentNullException: Value cannot be null.
Parameter name: session
   at NServiceBus.IMessageSessionExtensions.Send(IMessageSession session, Object message)
   at ServiceControl.Audit.Auditing.AuditPersister.<ProcessedMessage>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ServiceControl.Audit.Auditing.ImportFailedAudits.<Run>d__2`2.MoveNext()
```

when attempting to re-import audit messages from the command line.

### Root cause

The failure is caused by wrong configuration of the DI infrastructure. The `ImportFailedAudits` type requested directly from the container is not initialized. Instead, the `AuditIngestionComponent` type should be requested from the container.

### Who's affected

Affected are all ServiceControl users since version 4.0.1

**Comment by kbaley** [comment]
We have triaged this issue and will be considering it for inclusion in one of the upcoming maintenance releases for this package.
