### ISSUE TITLE
Invoke-ServiceControlAuditInstanceUpgrade failing to update SQL transport audit instance

### ISSUE THREAD

**Issue by danieloluyomi-cal** [Particular/ServiceControl#2333]
When running the powershell cmdlet to update a SQL transport service control audit instance from v4.13.2 to v4.14.0, I'm met with the following error message:

```powershell
Upgrade Failed: Access to the path 'C:\NServiceBus\Particular.ServiceControl.Bus.Audit\Bin\Autofac.dll' is denied.
```
I am using an account with local admin permissions and running the cmdlet under the ServiceControl Management PowerShell program. 

I have also attempted to run the upgrade via the Management GUI which returns a similar error:

```System.UnauthorizedAccessException: Access to the path 'C:\NServiceBus\Particular.ServiceControl.Bus.Audit\Bin\Autofac.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at ServiceControlInstaller.Engine.FileSystem.FileUtils.DeleteDirectory(String path, Boolean recursive, Boolean contentsOnly, String[] excludes)
   at ServiceControlInstaller.Engine.Instances.ServiceControlAuditInstance.UpgradeFiles(String zipFilePath)
   at ServiceControl.Config.Framework.Modules.ServiceControlInstallerBase.Upgrade(ServiceControlBaseService instance, ServiceControlUpgradeOptions upgradeOptions, IProgress`1 progress)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Commands.UpgradeAuditInstanceCommand.<UpgradeAuditInstance>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Commands.UpgradeAuditInstanceCommand.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Framework.Commands.AwaitableAbstractCommand`1.<ServiceControl-Config-Framework-Commands-ICommand<T>-Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

According to the existing documentation, the following steps occur when invoking an instance upgrade.

1. Prompt for additional required information, i.e. new mandatory settings introduced in the newer version
2. Stop the service
3. Remove the old binaries for ServiceControl and the configured transport
4. Run the new binaries to create required queues
5. Start the service

It looks like its failing at step 3.

This is running on a Windows Server 2019 VM

**Comment by mikeminutillo** [comment]
@danieloluyomi-cal it looks like we might be advancing to step 3 before step 2 has completely finished. This may be a regression of https://github.com/Particular/ServiceControl/issues/907 which was fixed in 4.4.0.

While we look into it, can you try to manually stop the instance before performing the update? Wait for the service to stop and ensure that the ServiceControl.exe process is no longer running before attempting the update.

**Comment by TraGicCode** [comment]
Hey @mikeminutillo ,

Does your team have an idea on what is going on here along with if this will be fixed soon?  I'm running into this issue when i'm running automated acceptance tests for my puppet module.

https://github.com/TraGicCode/tragiccode-nservicebusservicecontrol/runs/5417072717?check_suite_focus=true

I've had to put a hack in that sleeps for over 10 seconds which is not ideal.

**Comment by lailabougria** [comment]
Hi @TraGicCode, It's on our radar, but unfortunately we don't have any insight on when this will be fixed at the moment. Once this is fixed we'll make sure to update this issue accordingly so that you receive a notification.
