### ISSUE TITLE
The index $ExpiryProcessedMessageIndex was disabled message in logs

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceControl#2533]
Versions:
ServiceControl = 4.16.0
ServicePulse     = 1.25.4

Hello,

I'm noticing the following showing up in our servicecontrol production logs

```
2021-05-06 04:34:15.1848|43|Error|ServiceControl.Audit.Infrastructure.RavenDB.Expiration.AuditMessageCleaner|Unable to cleanup audit messages. The index $ExpiryProcessedMessageIndex was disabled.
Raven.Abstractions.Exceptions.IndexDisabledException: The index has been disabled due to errors
   at Raven.Database.Indexing.Index.IndexQueryOperation.<Query>d__17.MoveNext()
   at Raven.Database.Util.ActiveEnumerable`1..ctor(IEnumerable`1 enumerable)
   at Raven.Database.Actions.QueryActions.DatabaseQueryOperation.Init()
   at Raven.Database.Actions.QueryActions.<>c__DisplayClass2_0.<Query>b__0(IStorageActionsAccessor accessor)
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext)
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action)
   at Raven.Database.Actions.QueryActions.Query(String index, IndexQuery query, CancellationToken externalCancellationToken)
   at ServiceControl.Infrastructure.RavenDB.Extensions.Query[TState](DocumentDatabase db, String index, IndexQuery query, CancellationToken externalCancellationToken, Action`2 onItem, TState state) in /_/src/ServiceControl.Infrastructure.RavenDB/Extensions.cs:line 13
   at ServiceControl.Audit.Infrastructure.RavenDB.Expiration.AuditMessageCleaner.Clean(Int32 deletionBatchSize, DocumentDatabase database, DateTime expiryThreshold, CancellationToken token) in /_/src/ServiceControl.Audit/Infrastructure/RavenDB/Expiration/AuditMessageCleaner.cs:line 21
```

Couple of questions:
1. I would assume this means until it's resolved cleanup of old audit message will not happen.  Is this correct?
2. Are there any failed custom checks that are supposed to show up in servicecontrol to help visually let the user know they need to  step in?
3. Is there any documentation I can use to help understand what went wrong and/or how to fix the issue the recommended way?

**Comment by lailabougria** [comment]
Hi @TraGicCode,

1. The cleanup uses the index to query for data. If the index is disabled, cleanup will keep failing.
2. We've just released [ServiceControl 4.17](https://github.com/Particular/ServiceControl/releases/tag/4.17.0) which introduces a custom check notifying you of disabled indexes.
3. We have a [troubleshooting section on ServiceControl](https://docs.particular.net/servicecontrol/troubleshooting), and a dedicated section on disabled indexes is available [here](https://docs.particular.net/servicecontrol/troubleshooting#indexes-get-corrupted) as well. Once the index is disabled, it needs to be rebuilt, which needs to be done in ServiceControl maintenance mode. In most cases we see the indexes being disabled when RavenDB runs out of storage (there's a custom check verifying the storage as well), but it may be caused by other problems as well. 

I hope that helps!

**Comment by TraGicCode** [comment]
Hey @lailabougria ,

We will perform steps 2 and 3 and will report back if we have any issues.

Thank you

**Comment by TraGicCode** [comment]
Hey @lailabougria ,

This all worked perfectly.  

Thank you!

**Comment by lailabougria** [comment]
Thanks for the feedback @TraGicCode, I'm happy it helped 🎉
