### ISSUE TITLE
ServiceControl Audit instance throws System.UnauthorizedAccessException after upgrading to 4.19.0

### ISSUE THREAD

**Issue by Asopus** [Particular/ServiceControl#2655]
## Symptoms

When starting ServiceControl Audit instance, after creation or upgrade, the startup fails. The following exception can be found in the logs:

```
Application: ServiceControl.Audit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at Raven.Database.Server.AssemblyExtractor.Extract(System.Reflection.Assembly, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,AssemblyToExtract>>, System.String)
   at Raven.Database.Server.AssemblyExtractor.ExtractEmbeddedAssemblies(Raven.Database.Config.InMemoryRavenConfiguration)
   at Owin.AppBuilderExtensions.UseRavenDB(Owin.IAppBuilder, Raven.Database.Server.RavenDBOptions)
   at Raven.Database.Server.OwinHttpServer.<.ctor>b__4_0(Owin.IAppBuilder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(Microsoft.Owin.Hosting.Engine.StartContext)
   at Raven.Database.Embedded.OwinEmbeddedHost.Configure(System.Action`1<Owin.IAppBuilder>, Microsoft.Owin.Hosting.StartOptions)
   at Raven.Database.Server.OwinHttpServer..ctor(Raven.Database.Config.InMemoryRavenConfiguration, Raven.Database.DocumentDatabase, Boolean, System.Action`1<Raven.Database.Server.RavenDBOptions>)
   at Raven.Server.RavenDbServer.Initialize(System.Action`1<Raven.Database.Server.RavenDBOptions>)
   at Raven.Database.Client.EmbeddedDocumentStore.Initialize()
   at Raven.Client.Embedded.EmbeddableDocumentStore.Initialize()
   at ServiceControl.Audit.Infrastructure.RavenDB.EmbeddedRavenDbHostedService+<StartAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Audit.Infrastructure.Hosting.Commands.CommandRunner+<Execute>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Audit.Program+<Main>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Audit.Program.<Main>(System.String[])
```

## Who's affected

Any ServiceControl Audit instance on version 4.19.x or 4.20.x that is running under a service account which does not have write privileges in the working directory of the instance.

## Workaround

The impacted audit instance needs to run in the context of an account that has enough privileges to the ServiceControl working directory e.g. `LOCAL SYSTEM`. After that single run, the instance can be switched back to the original user. 
The change can be done e.g. via Service Control Management Utility:

![image](https://user-images.githubusercontent.com/1092707/139050363-d95f700f-8bcc-452a-a4b4-6858aee15bf9.png)

## Cause

The embedded RavenDB instance includes embedded assemblies that it extracts when it starts up. The default location is the working folder for the running application. In this case, it's the ServiceControl Audit instance installation folder. If the files are already there and they are the right versions, this step is skipped.

In 4.18, when an instance is upgraded, we start the RavenDB instance during the upgrade process. The upgrade requires elevated permissions, so this works. The assemblies are extracted. When the instance runs afterwards, the assemblies are there and the process is skipped..

In 4.19, we do not start the RavenDB instance during the upgrade process. That means that the first time RavenDB attempts to extract it's assemblies, it is not in an elevated permission context. It is running with the credentials that the ServiceControl instance is configured to run with normally. These credentials may not have permission to write to the working folder of the running ServiceControl process. If not, then a failure occurs and the embedded database fails to start with the exception provided above.

If the credentials do have permission to write to the working folder (such as if the instance keeps the default configuration to run under the Local System account), then this process succeeds.

## Fix

The audit instance will now attempt to extract the assemblies during the setup process, which is run under an administrative account during endpoint creation and upgrades. #2657

<details>
<summary>Original Issue</summary>
Hello

I have an issue upgrading an audit instance from 4.15.1 to 4.19.0 (or any subsequent version, even the latest one).
After the upgrade, the audit instance crashes on repeat with the following stacktrace:

```
Application: ServiceControl.Audit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at Raven.Database.Server.AssemblyExtractor.Extract(System.Reflection.Assembly, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,AssemblyToExtract>>, System.String)
   at Raven.Database.Server.AssemblyExtractor.ExtractEmbeddedAssemblies(Raven.Database.Config.InMemoryRavenConfiguration)
   at Owin.AppBuilderExtensions.UseRavenDB(Owin.IAppBuilder, Raven.Database.Server.RavenDBOptions)
   at Raven.Database.Server.OwinHttpServer.<.ctor>b__4_0(Owin.IAppBuilder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(Microsoft.Owin.Hosting.Engine.StartContext)
   at Raven.Database.Embedded.OwinEmbeddedHost.Configure(System.Action`1<Owin.IAppBuilder>, Microsoft.Owin.Hosting.StartOptions)
   at Raven.Database.Server.OwinHttpServer..ctor(Raven.Database.Config.InMemoryRavenConfiguration, Raven.Database.DocumentDatabase, Boolean, System.Action`1<Raven.Database.Server.RavenDBOptions>)
   at Raven.Server.RavenDbServer.Initialize(System.Action`1<Raven.Database.Server.RavenDBOptions>)
   at Raven.Database.Client.EmbeddedDocumentStore.Initialize()
   at Raven.Client.Embedded.EmbeddableDocumentStore.Initialize()
   at ServiceControl.Audit.Infrastructure.RavenDB.EmbeddedRavenDbHostedService+<StartAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Audit.Infrastructure.Hosting.Commands.CommandRunner+<Execute>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Audit.Program+<Main>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Audit.Program.<Main>(System.String[])
```

I have also tried upgrading another instance to the version just below (4.18.0) which seems to work fine.

Kind regards
Pieter
</details>

**Comment by tmasternak** [comment]
@Asopus the fix is out in https://github.com/Particular/ServiceControl/releases/tag/4.21.0
