### ISSUE TITLE
Cannot start 4.18.0 Servicecontrol instance in maintenance mode

### ISSUE THREAD

**Issue by Asopus** [Particular/ServiceControl#2680]
Hello

After upgrading our service control instances to 4.18.0, we can't bring them into maintenance mode anymore. Clicking the 'Start Maintenance Mode' button generates the following stacktrace in the event viewer:

```
Application: ServiceControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.HttpListenerException
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(System.Net.HttpListener, System.Func`2<System.Collections.Generic.IDictionary`2<System.String,System.Object>,System.Threading.Tasks.Task>, System.Collections.Generic.IList`1<System.Collections.Generic.IDictionary`2<System.String,System.Object>>, System.Collections.Generic.IDictionary`2<System.String,System.Object>, System.Func`2<System.String,System.Func`6<System.Diagnostics.TraceEventType,Int32,System.Object,System.Exception,System.Func`3<System.Object,System.Exception,System.String>,Boolean>>)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(System.Func`2<System.Collections.Generic.IDictionary`2<System.String,System.Object>,System.Threading.Tasks.Task>, System.Collections.Generic.IDictionary`2<System.String,System.Object>)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(Owin.IAppBuilder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(Microsoft.Owin.Hosting.Engine.StartContext)
   at Raven.Database.Server.OwinHttpServer.EnableHttpServer(Raven.Database.Config.InMemoryRavenConfiguration)
   at Raven.Server.RavenDbServer.Initialize(System.Action`1<Raven.Database.Server.RavenDBOptions>)
   at Raven.Database.Client.EmbeddedDocumentStore.Initialize()
   at Raven.Client.Embedded.EmbeddableDocumentStore.Initialize()
   at ServiceControl.Infrastructure.RavenDB.RavenBootstrapper.StartRaven(Raven.Client.Embedded.EmbeddableDocumentStore, ServiceBus.Management.Infrastructure.Settings.Settings, Boolean)
   at Particular.ServiceControl.MaintenanceBootstrapper+<Run>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Particular.ServiceControl.Commands.CommandRunner+<Execute>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Particular.ServiceControl.Program+<Main>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Particular.ServiceControl.Program.<Main>(System.String[])
```

I suspect it has something to do with exposing the RavenDb because setting the `ServiceControl/ExposeRavenD` key to `True` and starting the instance normally generates the same error. Previous version had no such issue (4.15.1).

Kr
Pieter

**Comment by tmasternak** [comment]
Hi Pieter, I suspect that this can be caused by insufficient privileges being granted to the account running the ReavenDB instance. Let me try reproducing that. I'll keep you posted.

**Comment by tmasternak** [comment]
@Asopus could you check what ist the url registration for the Maintenace port for Raven using:
> netsh http show urlacl

It looks that the URL acl registration is not there or it does not assign proper priveledges for the account running the service.

**Comment by Asopus** [comment]
> @Asopus could you check what ist the url registration for the Maintenace port for Raven using:
> 
> > netsh http show urlacl
> 
> It looks that the URL acl registration is not there or it does not assign proper priveledges for the account running the service.

```
 Reserved URL            : http://<MACHINENAME>:45000/
        User: BUILTIN\Users
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;BU)

    Reserved URL            : http://+:45001/
        User: BUILTIN\Users
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;BU)
```

I checked an instance running with an earlier version and there, both port and maintenance port are reserved with the \<MACHINENAME> included in the url, i.e.:

```
 Reserved URL            : http://<MACHINENAME>:45000/
        User: BUILTIN\Users
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;BU)

 Reserved URL            : http://<MACHINENAME>:45001/
        User: BUILTIN\Users
            Listen: Yes
            Delegate: No
            SDDL: D:(A;;GX;;;BU)
```

**Comment by tmasternak** [comment]
It looks that the problem might have been caused by https://github.com/Particular/ServiceControl/issues/1643 I think that RavenDB is using `+` in the URL only when `localhost` is passed as the machine name, and otherwise, it will use the `<MACHINENAME>` as is. 

I'll verify if that is true and comment here.

**Comment by tmasternak** [comment]
@Asopus I was able to reproduce the issue. It looks that the URLACL registrations are the root cause. The workaround is the delete the URLACL for the http://+:45001/ using:

> netsh http delete urlacl http://+:45001/

and recreate it with the machine name like:

> netsh http add urlacl url=http://<MACHINENAME>:40001/ user="BUILTIN\Users"

**Comment by Asopus** [comment]
> @Asopus I was able to reproduce the issue. It looks that the URLACL registrations are the root cause. The workaround is the delete the URLACL for the http://+:45001/ using:
> 
> > netsh http delete urlacl http://+:45001/
> 
> and recreate it with the machine name like:
> 
> > netsh http add urlacl url=http://:40001/ user="BUILTIN\Users"

Thanks, we'll use the workaround when maintenance is required.
Do you have an idea which release will contain the patch for this bug?

**Comment by tmasternak** [comment]
> Do you have an idea which release will contain the patch for this bug?

I'll let you know as soon as I know.

**Comment by tmasternak** [comment]
@Asopus the fix will be out with the release going out next week.

**Comment by tmasternak** [comment]
@Asopus the fix is out in https://github.com/Particular/ServiceControl/releases/tag/4.21.0
