### ISSUE TITLE
DataMigrations might fail due to index corruptions and prevent ServiceControl from starting

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#2865]
When ServiceControl is started it first creates the indexes and then runs the data migrations that implement `IDataMigration`. Unfortunately when indexes got corrupted the data migrations might fail to be executed and throw an `InvalidOperationException` that then prevents ServiceControl from starting

Below is a stack trace of such a case when the KnownEndpointsIndex got corrupted, which then caused `PurgeKnownEndpointsWithTemporaryIdsThatAreDuplicateDataMigration` to fail.  

```
Exception Info: System.InvalidOperationException

   at Raven.Client.Connection.ServerClient.Query(System.String, Raven.Abstractions.Data.IndexQuery, System.String[], Boolean, Boolean)

   at Raven.Client.Document.DocumentQuery`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ExecuteActualQuery()

   at Raven.Client.Document.DocumentQuery`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_QueryResult()

   at Raven.Client.Linq.RavenQueryProviderProcessor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ExecuteQuery[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()

   at Raven.Client.Linq.RavenQueryInspector`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetEnumerator()

   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)

   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)

   at ServiceControl.Infrastructure.RavenDB.PurgeKnownEndpointsWithTemporaryIdsThatAreDuplicateDataMigration.Migrate(Raven.Client.IDocumentStore)

   at ServiceControl.Infrastructure.RavenDB.EmbeddedRavenDbHostedService+<SetupDatabase>d__5.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__12.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Particular.ServiceControl.Commands.CommandRunner+<Execute>d__1.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Particular.ServiceControl.Program+<Main>d__0.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Particular.ServiceControl.Program.<Main>(System.String[])
```

Maybe it would be even better to make sure to find the root cause of how the index creation can be successful in https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/RavenDB/EmbeddedRavenDbHostedService.cs#L33-L35

```csharp
            var indexProvider = CreateIndexProvider(setupContext.IndexAssemblies);
            await IndexCreation.CreateIndexesAsync(indexProvider, documentStore)
                .ConfigureAwait(false);
```

while the indexes are still corrupt.

## Workaround

[Reset the `KnownEndpointIndex`](https://docs.particular.net/servicecontrol/troubleshooting#corrupted-indexes)

**Comment by danielmarbach** [comment]
We have prioritized your issue near the top of our list and will be working on it as soon as we can.
