### ISSUE TITLE
Excessive logging and system resource utilization when message pump receive operations fails

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#3318]
It seems SC lacks some failure logic and just goes in an unbounded infinite loop:

1. Flooding should never occur
2. Consecutive failures in the receive message should result in termination of the process

Likely this is due to transitioning to the transport seam which could have resulted in some failure handling to no longer take place.

Background info is that I somehow broke my installation and noticed that my log was flooded with the following:

```
2022-12-13 12:30:53.0200|10|Warn|NServiceBus.Transport.AzureServiceBus.MessagePump|Failed to receive a message. Exception: Method not found: 'System.Threading.Tasks.Task`1<!0> Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(System.TimeSpan, System.Threading.CancellationToken)'.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!0> Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(System.TimeSpan, System.Threading.CancellationToken)'.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<ReceiveMessagesAsyncInternal>d__42.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__41_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__23`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__23`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<ReceiveMessagesAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<ReceiveMessagesAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<ReceiveMessagesAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<ReceiveMessageAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<ReceiveMessage>d__25.MoveNext() in /_/src/Transport/Receiving/MessagePump.cs:line 165
```

**Comment by tmasternak** [comment]
@ramonsmits do you have any instructions on how this can be reproduced? Do we have any clients that were affected by this problem?

**Comment by ramonsmits** [comment]
@tmasternak No, just my own observation. As for reproducing. Maybe just disabling your network adapter might work?

**Comment by tmasternak** [comment]
Fixed in https://github.com/Particular/ServiceControl/pull/3379
