### ISSUE TITLE
Audit instances logs to the installation folder

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#3364]
As of version 4.26 new audit instances will try to log to the installation folder and fail on startup since its unlikely for the user account to have write permissions there

### Symptoms

ServiceControl audit fails on startup with 

```
System.UnauthorizedAccessException: Access to the path '{installation-path}\RavenDBServer\Packages\NuGet$1\test.file' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Raven.Server.Utils.IOExtensions.TryHandlingError(String directory, Int32 i, Exception e)
```

Relates to https://github.com/Particular/ServiceControl/issues/3253

### Workaround 

As a workaround, grant the user account _write_ permissions to the ServiceControl audit instance's installation directory and subdirectories. 

The default installation path for Service Control Audit instances is 
```
C:\Program Files (x86)\Particular Software\<instance name>
```

**Comment by andreasohlund** [comment]
Embedded raven has an explicit `logsPath` option that could be used to solve this, a quick spike proved that it works

https://github.com/Particular/ServiceControl/pull/3367
