### ISSUE TITLE
RabbitMQ connection string using amqps:// format does not work for Monitoring instance

### ISSUE THREAD

**Issue by Bishbulb** [Particular/ServiceControl#3401]
We are using Amazon MQ with the RabbitMQ broker that only allows secure connections, and thus uses the amqps URI spec:
https://www.rabbitmq.com/uri-spec.html

The only way I was able to get ServiceControl to communicate with this RabbitMQ instance was to specify the connection string in the following format:
`amqps://username:password@some-guid-identifier.mq.us-east-1.amazonaws.com:5671`

However, if I take the exact same value and use it as the connection string for a Monitoring instance, the monitoring service throws the following exception on startup:
```
Exception Info: System.ArgumentException
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(System.String, Int32, System.Text.StringBuilder, Boolean, System.String ByRef, System.String ByRef)
   at System.Data.Common.DbConnectionOptions.ParseInternal(System.Collections.Hashtable, System.String, Boolean, System.Collections.Hashtable, Boolean)
   at System.Data.Common.DbConnectionOptions..ctor(System.String, System.Collections.Hashtable, Boolean)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(System.String)
   at ServiceControl.Transports.RabbitMQ.QueueLengthProvider+QueryExecutor.Initialize()
   at ServiceControl.Transports.RabbitMQ.QueueLengthProvider.Start()
   at NServiceBus.Features.FeatureStartupTaskController.Start(NServiceBus.ObjectBuilder.IBuilder, NServiceBus.IMessageSession)
   at NServiceBus.Features.FeatureActivator+<StartFeatures>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.StartableEndpoint+<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.HostingComponent+<Start>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.ExternallyManagedContainerHost+<Start>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.Extensions.Hosting.NServiceBusHostedService+<StartAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ServiceControl.Monitoring.CommandRunner+<Run>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Monitoring.Program+<Main>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Monitoring.Program.<Main>(System.String[])
```

Is it possible to have the Monitoring instance modified so that it can accept the same connection string format?

**Comment by kbaley** [comment]
It looks like we're parsing AMQP connection strings for error instances but not for [monitoring instances](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Transports.RabbitMQ/QueueLengthProvider.cs#L145).

**Comment by bording** [comment]
@Bishbulb While I do think we should update monitoring instances to also accept the AMQP format for connection strings, you should able to use our [custom connection string format](https://docs.particular.net/transports/rabbitmq/connection-settings#connection-string-options) to connect to RabbitMQ brokers that require secure connections.

For the example connection string you provided, `amqps://username:password@some-guid-identifier.mq.us-east-1.amazonaws.com:5671`, the equivalent connection string that will work is:

`host=some-guid-identifier.mq.us-east-1.amazonaws.com;username=username;password=password;UseTls=true`

**Comment by Bishbulb** [comment]
@bording thanks for the tip regarding UseTls, I think that was what was preventing access when I tried that format earlier.

**Comment by kbaley** [comment]
In the meantime, we've added the issue to our backlog. It's eligible to be picked up for a future release, but we can't provide a firm timeline for the moment. Hopefully the workaround will unblock you in the meantime.

**Comment by mozerov** [comment]
The workaround seems to not work for CloudAMQP connection strings. Tried different combinations with cluster/host addresses with/without port but still getting different exceptions 😞

**Comment by bording** [comment]
@mozerov I would need to see some more information to be able to help you. What are you actually trying? What exceptions are you seeing?

**Comment by bording** [comment]
@mozerov Please take a look at my earlier comment in this issue: https://github.com/Particular/ServiceControl/issues/3401#issuecomment-1424815532

ServiceControl cannot use the `amqps://` connection string format, but you can take the info provided in the connection string that CloudAMQP gave you and convert it into a connection string that ServiceControl will understand.

**Comment by mozerov** [comment]
@bording I did exactly that and I mentioned this in my previous comment (maybe you missed it somehow)

> Tried to change the connection string according to the workaround provided in _this_ comment but ServiceControl Monitoring service is still unable to start.

**Comment by bording** [comment]
@mozerov I would need to see the details of the connection string that you were given and how you attempted to convert it to be able to help you further. If you're okay with sharing that information with us, please use https://particular.net/support to start a non-critical support case with the information.

Otherwise, you would need to do a few things. First, verify that the `amqps://` connection string you using works for connecting to the broker at all outside of ServiceControl. For example with an NServiceBus endpoint or directly using the RabbitMQ client.

If it does, then you would need to double check how you converted it, because if the `amqps://` connection string is valid, it will definitely work when converted to the other format.

**Comment by mozerov** [comment]
Hi @bording,

> First, verify that the amqps:// connection string you using works for connecting to the broker at all outside of ServiceControl. For example with an NServiceBus endpoint or directly using the RabbitMQ client.
Surely I did this :)

> If it does, then you would need to double check how you converted it, because if the amqps:// connection string is valid, it will definitely work when converted to the other format.
Agree, but for some reason it doesn't :(

I ended up creating a support ticket. Thanks for your help so far.

**Comment by mozerov** [comment]
Thanks to the support we have found the issue. I was missing the virtualhost configuration in the Connection String.

**Comment by eric-alcidion** [comment]
Any ETA on this one? 
The same amqps:// string works everywhere in the stack except Monitoring.

**Comment by bording** [comment]
@eric-alcidion We're currently working on a new version of the RabbitMQ transport and integrating it into ServiceControl. The good news is that as part of that work, this issue will be fixed as well.

I don't have a specific ETA for a new ServiceControl release containing these changes, but it shouldn't be too much longer.
