### ISSUE TITLE
 Service Control Audit will not start after ServiceControl update to 4.29.0 

### ISSUE THREAD

**Issue by cquirosj** [Particular/ServiceControl#3434]
### Symptoms

After upgrading to version 4.29.0 the application fails to start.  ServiceControl Audit instance log will show entries like these:

Operations, Server, Raven.Server.RavenServer, Could not open the server store, EXCEPTION: System.InvalidOperationException: Could not access some of the specified paths. Please check if you have sufficient privileges to access following paths:
Key: 'Logs.Microsoft.ConfigurationPath' Path: 'C:\Program Files (x86)\Particular Software\ServiceControl.Audit\RavenDBServer\settings.logs.microsoft.json$1' Error: 'Access to the path 'C:\Program Files (x86)\Particular Software\ServiceControl.Audit\RavenDBServer\settings.logs.microsoft.json$1' is denied.'

at Raven.Server.Config.RavenConfiguration.CheckDirectoryPermissions() in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Server\Config\RavenConfiguration.cs:line 509
at Raven.Server.ServerWide.ServerStore.Initialize() in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Server\ServerWide\ServerStore.cs:line 573
at Raven.Server.RavenServer.Initialize() in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Server\RavenServer.cs:line 312

### Who's affected

Users of version 4.29.0 who run ServiceControl under a user with limited write access to its installation folder

### Root cause

Some versions of RavenDb 5.4.100 and lower test the configuration files can be written at start-up. RavenDb team has updated this behavior for the 'Logs.Microsoft.ConfigurationPath' configuration entry, making it read-only. This [change](https://github.com/ravendb/ravendb/commit/3cdc874bb9254dd92e987044af6b5ac5fb5805c4) is available starting on RavenDb 5.4.101

**Comment by cquirosj** [comment]
Solved by #3435
