### ISSUE TITLE
Monitoring Timeout MSMQ queue is not created during installation

### ISSUE THREAD

**Issue by fourpastmidnight** [Particular/ServiceControl#3488]
#### Description

I fresh installed a new Monitoring instance using `New-MonitoringInstance`. But the instance failed to start due to queues not being created.

#### Expected behavior

I expected that, much as `New-ServiceControlInstance` creates the necessary queues, including the `error` and `error.log` queues, that the required queues would also be created.

#### Actual behavior

The queues were not created.

#### Versions

4.29.3

### Steps to reproduce

1. Create a new monitoring instance using the MSMQ transport via `New-MonitoringInstance`
2. Observe that the newly created service immediately crashes.
3. Observe in the log files that there are errors due to queues not being created.

### Relevant log output

```shell
------------------------------------------------------------
ServiceControl Monitoring Version:				4.29.3+185657adcc17d5832d9c3093f55f019bd80862ec
Selected Transport:					ServiceControl.Transports.Msmq.MsmqTransportCustomization, ServiceControl.Transports.Msmq
-------------------------------------------------------------
2023-04-07 16:51:39.7858|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring] is running with [Everyone] with AccessRights set to [GetQueueProperties, GetQueuePermissions]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2023-04-07 16:51:39.8639|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts] does not exist
2023-04-07 16:51:39.8639|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.TimeoutsDispatcher] does not exist
2023-04-07 16:51:39.9734|6|Fatal|NServiceBus.ReceiveComponent|Receiver Timeout Message Processor failed to initialize.
System.Exception: The queue FormatName:DIRECT=OS:DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts does not exist. Run the CreateQueues.ps1 script included in the project output, or enable queue creation on startup using EndpointConfiguration.EnableInstallers(). ---> System.Messaging.MessageQueueException: The queue does not exist or you do not have sufficient permissions to perform the operation.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 188
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 201
   at NServiceBus.Transport.Msmq.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings) in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 42
   at NServiceBus.Transport.Msmq.CompositePump.<Init>d__3.MoveNext() in /_/src/NServiceBus.Transport.Msmq/CompositePump.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.ReceiveComponent.<PrepareToStart>d__5.MoveNext() in /_/src/NServiceBus.Core/Receiving/ReceiveComponent.cs:line 174

2023-04-07 17:23:11.8889|7|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring] is running with [Everyone] with AccessRights set to [GetQueueProperties, GetQueuePermissions]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2023-04-07 17:23:12.9045|7|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts] does not exist
2023-04-07 17:23:12.9045|7|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.TimeoutsDispatcher] does not exist
2023-04-07 17:23:13.0920|7|Fatal|NServiceBus.ReceiveComponent|Receiver Timeout Message Processor failed to initialize.
System.Exception: The queue FormatName:DIRECT=OS:DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts does not exist. Run the CreateQueues.ps1 script included in the project output, or enable queue creation on startup using EndpointConfiguration.EnableInstallers(). ---> System.Messaging.MessageQueueException: The queue does not exist or you do not have sufficient permissions to perform the operation.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 188
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 201
   at NServiceBus.Transport.Msmq.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings) in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 42
   at NServiceBus.Transport.Msmq.CompositePump.<Init>d__3.MoveNext() in /_/src/NServiceBus.Transport.Msmq/CompositePump.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.ReceiveComponent.<PrepareToStart>d__5.MoveNext() in /_/src/NServiceBus.Core/Receiving/ReceiveComponent.cs:line 174
2023-04-07 17:24:23.0578|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring] is running with [Everyone] with AccessRights set to [GetQueueProperties, GetQueuePermissions]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2023-04-07 17:24:23.1668|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts] does not exist
2023-04-07 17:24:23.1668|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.TimeoutsDispatcher] does not exist
2023-04-07 17:24:23.2761|6|Fatal|NServiceBus.ReceiveComponent|Receiver Timeout Message Processor failed to initialize.
System.Exception: The queue FormatName:DIRECT=OS:DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts does not exist. Run the CreateQueues.ps1 script included in the project output, or enable queue creation on startup using EndpointConfiguration.EnableInstallers(). ---> System.Messaging.MessageQueueException: The queue does not exist or you do not have sufficient permissions to perform the operation.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 188
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 201
   at NServiceBus.Transport.Msmq.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings) in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 42
   at NServiceBus.Transport.Msmq.CompositePump.<Init>d__3.MoveNext() in /_/src/NServiceBus.Transport.Msmq/CompositePump.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.ReceiveComponent.<PrepareToStart>d__5.MoveNext() in /_/src/NServiceBus.Core/Receiving/ReceiveComponent.cs:line 174
2023-04-07 17:25:28.6555|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring] is running with [Everyone] with AccessRights set to [GetQueueProperties, GetQueuePermissions]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2023-04-07 17:25:28.7805|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts] does not exist
2023-04-07 17:25:28.7805|6|Warn|NServiceBus.Transport.Msmq.QueuePermissions|Queue [DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.TimeoutsDispatcher] does not exist
2023-04-07 17:25:28.8742|6|Fatal|NServiceBus.ReceiveComponent|Receiver Timeout Message Processor failed to initialize.
System.Exception: The queue FormatName:DIRECT=OS:DSC4INSTALLTST0\private$\[REDACTED].DSC4INSTALLTST0.ServiceControl.Monitoring.Timeouts does not exist. Run the CreateQueues.ps1 script included in the project output, or enable queue creation on startup using EndpointConfiguration.EnableInstallers(). ---> System.Messaging.MessageQueueException: The queue does not exist or you do not have sufficient permissions to perform the operation.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 188
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.Msmq.MessagePump.QueueIsTransactional() in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 201
   at NServiceBus.Transport.Msmq.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings) in /_/src/NServiceBus.Transport.Msmq/MessagePump.cs:line 42
   at NServiceBus.Transport.Msmq.CompositePump.<Init>d__3.MoveNext() in /_/src/NServiceBus.Transport.Msmq/CompositePump.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.ReceiveComponent.<PrepareToStart>d__5.MoveNext() in /_/src/NServiceBus.Core/Receiving/ReceiveComponent.cs:line 174
```

#### Workarounds

The log file suggests runing `CreateQueues.ps1`.

#### Possible solutions

Create the queues when `New-MonitoringInstance` is invoked.

**Comment by fourpastmidnight** [comment]
The only problem with the workaround is that `CreateQueues.ps1` is not part of the Monitoring instance installation, and is not part of the ZIP archive provided on the releases page. So, this workaround is, indeed, very inconvenient.

**Comment by fourpastmidnight** [comment]
Ping--can anyone comment on this? I've re-read the docs and there's no mention of anything else needing to be done to stand up a monitoring instance outside of invoking `New-MonitoringInstance`.

**Comment by WilliamBZA** [comment]
Definitely a bug, this shouldn't happen. I'll let you know once we start addressing this

**Comment by fourpastmidnight** [comment]
I thank you again.

**Comment by fourpastmidnight** [comment]
TY!

**Comment by WilliamBZA** [comment]
FYI this has been released now, it should be working
