### ISSUE TITLE
Raven.Server.RavenServer, Could not start server, EXCEPTION: System.IO.IOException: Failed to bind to address http://127.0.0.1:44445: address already in use.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#3521]
#### Description

The RavenDB log file can contain the following error:

> Raven.Server.RavenServer, Could not start server, EXCEPTION: System.IO.IOException: Failed to bind to address http://127.0.0.1:44445: address already in use.

It might be related to the following issue:

- https://github.com/Particular/ServiceControl/issues/3520

It is unknown if SC audit instance is gracefully handling this situation. If the issues are related likely it is not.

It might indicate a lingering old RavenDB server process instance that was not properly terminated.

#### Versions

4.30.0

### Steps to reproduce

Unknown

### Relevant log output

```shell
Time, Thread, Level, Source, Logger, Message, Exception
2023-05-10T05:32:11.4377715Z, 1, Operations, Server, Raven.Server.Program,  Build 54038, Version 5.4, SemVer 5.4.103, Commit dd4c794
 PID 1132, 64 bits, 2 Cores, Arch: X64
 7.999 GBytes Physical Memory, 2.435 GBytes Available Memory, 2.474 GBytes Calculated Available Memory, 0 Bytes Scratch Dirty Memory
 Using GC in server concurrent mode.
librvnpal Expected Version: 52000, librvnpal Current Version: 52000
2023-05-10T05:32:15.3848746Z, 1, Operations, Server, Raven.Server.RavenServer, Could not start server, EXCEPTION: System.IO.IOException: Failed to bind to address http://127.0.0.1:44445: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Raven.Server.RavenServer.Initialize() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Server\RavenServer.cs:line 270
2023-05-10T05:32:15.4061196Z, 1, Operations, Server, Raven.Server.Program, Failed to initialize the server, EXCEPTION: System.IO.IOException: Failed to bind to address http://127.0.0.1:44445: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Raven.Server.RavenServer.Initialize() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Server\RavenServer.cs:line 270
   at Raven.Server.Program.Main(String[] args) in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Server\Program.cs:line 185
2023-05-10T05:32:15.4066017Z, 1, Operations, Server, Raven.Server.Program, 
Port might be already in use.
Try running with an unused port.
You can change the port using one of the following options:
1) Change the ServerUrl property in setting.json file.
2) Run the server from the command line with --ServerUrl option.
3) Add RAVEN_ServerUrl to the Environment Variables.
```

**Comment by jpalac** [comment]
Have been unable to reproduce this issue. It could be a specific DynaTrace vs RavenDB compatibility issue which has already been reported to RaveDB [here](https://github.com/ravendb/ravendb/issues/16542)) and is part of [this support case](https://particular-software--c.vf.force.com/apex/Case?num=00079488).

**Comment by tmasternak** [comment]
The behavior introduced in #3590 ensures that an instance is not going to start if the embedded RavenDB process fails on startup. This makes the problem less problematic as customers get immediate feedback due to service stopping immediately after startup. /cc: @ramonsmits
