### ISSUE TITLE
RavenDB can timeout at start which causes a startup failure that sometimes is unrecoverable

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#3909]
### Describe the bug

RavenDB can timeout at start which causes a startup failure that sometimes is unrecoverable.

This can happen then there is some type of corruption in RavenDB that will take it longer than 30 seconds to recover thus start. ServiceControl will than crash at startup. If Windows Service Recovery is correctly setup Windows Service Control Manager will auto restart the instance after 1 minute but likely this fails again.

What is typical is that the "start" of the ServiceControl log file is short but clearly isn't fully initialized. In the Windows Task Manager is can be observed that the process eventually dies. 

### Steps to reproduce

No method known to reproduce.

### Relevant log output

```txt
2024-01-03 14:16:23.942 ERROR Unhandled exception was caught.
Raven.Client.Exceptions.Database.DatabaseLoadTimeoutException: Raven.Client.Exceptions.Database.DatabaseLoadTimeoutException: Database audit after 00:00:30 is still loading, try again later. Database initialization log:
[Load Database] 01/03/2024 14:15:53 :: Database 'audit' : Starting database initialization
[Load Database] 01/03/2024 14:15:53 :: Database 'audit' : Creating db.lock file
[Load Database] 01/03/2024 14:15:58 :: Database 'audit' : Initializing NotificationCenter
[Load Database] 01/03/2024 14:15:58 :: Database 'audit' : Initializing DocumentStorage

   at Raven.Server.Routing.RouteInformation.ThrowDatabaseLoadTimeoutWithLog(StringSegment databaseName, TimeSpan timeout, String log) in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Server\Routing\RouteInformation.cs:line 225
   at Raven.Server.Routing.RouteInformation.UnlikelyWaitForDatabaseToLoad(RequestHandlerContext context, Task`1 database, DatabasesLandlord databasesLandlord, StringSegment databaseName) in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Server\Routing\RouteInformation.cs:line 211
   at Raven.Server.Routing.RouteInformation.WaitForDb(Task databaseLoading) in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Server\Routing\RouteInformation.cs:line 247
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Server\Routing\RequestRouter.cs:line 384
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Server\RavenServerStartup.cs:line 255
The server at /databases/audit/stats responded with status code: ServiceUnavailable.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Raven.Client.Http.RequestExecutor.ThrowFailedToContactAllNodes[TResult](RavenCommand`1 command, HttpRequestMessage request) in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Client\Http\RequestExecutor.cs:line 1269
   at Raven.Client.Http.RequestExecutor.<ExecuteAsync>d__118`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Client\Http\RequestExecutor.cs:line 998
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Raven.Client.Http.RequestExecutor.<ExecuteAsync>d__118`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Client\Http\RequestExecutor.cs:line 1007
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Http.RequestExecutor.<UnlikelyExecuteAsync>d__109`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Client\Http\RequestExecutor.cs:line 631
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Documents.Operations.MaintenanceOperationExecutor.<SendAsync>d__13`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54092\src\Raven.Client\Documents\Operations\MaintenanceOperationExecutor.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Persistence.RavenDb.DatabaseSetup.<Execute>d__1.MoveNext() in /_/src/ServiceControl.Audit.Persistence.RavenDb5/DatabaseSetup.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Persistence.RavenDb.EmbeddedDatabase.<Connect>d__8.MoveNext() in /_/src/ServiceControl.Audit.Persistence.RavenDb5/EmbeddedDatabase.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Persistence.RavenDb.RavenDbEmbeddedPersistenceLifecycle.<Start>d__2.MoveNext() in /_/src/ServiceControl.Audit.Persistence.RavenDb5/RavenDbEmbeddedPersistenceLifecycle.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Infrastructure.MaintenanceBootstrapper.<Run>d__0.MoveNext() in /_/src/ServiceControl.Audit/Infrastructure/MaintenanceBootstrapper.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ServiceControl.Audit.Infrastructure.Hosting.Commands.CommandRunner.<Execute>d__1.MoveNext() in /_/src/ServiceControl.Audit/Infrastructure/Hosting/Commands/CommandRunner.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Program.<Main>d__1.MoveNext() in /_/src/ServiceControl.Audit/Program.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Audit.Program.<Main>(String[] args)
```

#### Workarounds

Launch the instance from the command line which spins up the RavenDB child process.

Steps:

1. Open ServiceControl Management utility
2. Launch the instance in maintenance mode via advanced settings
3. Click the RavenDB studio link in a modern browser (not internet explorer)
4. Observe that it shows errors/issues
5. Get the installation path for the instance
6. Open an elevated (as administrator) console
7. Navigate to the application folder of the instance
8. Launch the *.exe in that path with the correct `--serviceName=XXXXXX` argument. The value is the instance name shown in ServiceControl Management utility but can also be resolved via the Windows Service properties and review the "Path to executable" field and copy all its text.
9. Wait for RavenDB to recover

IMPORTANT: If a windows crash dialog is shown, then **do NOT close it**. Keep it open as this will keep the child process that hosts RavenDB. Eventually, RavenDB will recover its indexes. If you still have RavenDB studio open in the browser you should observe that the errors/issues will disappear.

10. Now you can close the crash dialog
11. Try starting the instance as normal
12. Observe that the instance likely shows a correct log startup sequence and that the instance remains running

#### Possible solutions

ServiceControl needs to gracefully handle RavenDB startup timeouts and give it more time to recover.

#### Additional information

The cause is corruption in the RavenDB5 indexes. Likely due to a server crash, forced ungracefull manual shutdown, or server reboot/shutdown.

It is very likely that your store IOPS are insufficient. If you observe that the instance ingest "fast" for the first few minutes and observe that the ingestion speed suddenly collapses then this is likely because the cloud provider its storage is rate limiting (slowing down) because the drive is exceeding its IOPS limits. 

Validate if the IOPS history for the drive isn't near the IOPS limit. If it is:

a. upscale the drive to an instance that allows more IOPS
b. outscale by adding multiple audit instances but each with its own dedicated drive (this can be on the same VM it the VM has sufficient CPU/RAM resources)
  - https://docs.particular.net/servicecontrol/servicecontrol-instances/remotes#overview-sharding-audit-messages-with-competing-consumers

**Comment by ramonsmits** [comment]
Fixed in https://github.com/Particular/ServiceControl/releases/tag/5.0.4 and backported to https://github.com/Particular/ServiceControl/releases/tag/4.33.2
