### ISSUE TITLE
Retry failed messages not working with Azure Storage Queues

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#396]
From Google Groups - https://groups.google.com/forum/#!topic/particularsoftware/ZfrIeFB4mHc

We're using ServiceControl to monitor our Azure Storage Queues but are having trouble retrying failed messages.

We can see 2 failed messages in ServiceInsight but when we attempt to retry the messages using ServicePulse nothing happens. We get the success message 'Retrying messages' in ServicePulse but the messages are never sent to the original queues.

When we try to open the failed messages in Service Insight (launched via ServicePulse) we get the following exception.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Particular.ServiceInsight.Desktop.SequenceDiagram.MessageInfo.get_ReceivingEndpoint() in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\SequenceDiagram\MessageInfo.cs:line 99
   at Particular.ServiceInsight.Desktop.SequenceDiagram.MessageInfo.UpdateIndicies() in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\SequenceDiagram\MessageInfo.cs:line 216
   at Particular.ServiceInsight.Desktop.SequenceDiagram.MessageInfo.set_Endpoints(IEnumerable`1 value)
   at Particular.ServiceInsight.Desktop.SequenceDiagram.MessageInfo..ctor(IEventAggregator eventAggregator, IWindowManagerEx windowManager, Func`1 exceptionDetailViewModel, SequenceDiagramViewModel viewModel, StoredMessage message, ReactiveList`1 endpoints) in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\SequenceDiagram\MessageInfo.cs:line 42
   at Particular.ServiceInsight.Desktop.SequenceDiagram.SequenceDiagramViewModel.<CreateMessages>b__a(StoredMessage m) in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\SequenceDiagram\SequenceDiagramViewModel.cs:line 145
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Particular.ServiceInsight.Desktop.SequenceDiagram.SequenceDiagramViewModel.CreateMessages(IEnumerable`1 messages) in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\SequenceDiagram\SequenceDiagramViewModel.cs:line 145
   at Particular.ServiceInsight.Desktop.SequenceDiagram.SequenceDiagramViewModel.Handle(SelectedMessageChanged message) in c:\BuildAgent\work\2be762a799648224\src\ServiceInsight.Desktop\SequenceDiagram\SequenceDiagramViewModel.cs:line 92
```
Our endpoints are running NServiceBus 5.0.1

ServiceControl 1.3.0
NServiceBus.Azure.Transports.WindowsAzureStorageQueues.5.3.5

ServiceInsight 1.2.1

**Comment by gbiellem** [comment]
@SeanFeldman  is lookng at this - see #397

**Comment by SeanFeldman** [comment]
@tomsave what queue SP showing you as the failed to process the message?

**Comment by gbiellem** [comment]
@SeanFeldman  Any Update?

**Comment by SeanFeldman** [comment]
@gbiellem I could not reproduce this, it worked as expected.
@tomsave could you provide a little more details?

**Comment by gbiellem** [comment]
I'm closing this since we can't reproduce it and the issue seems stale.  @tomsave  please feel free to reopen the issue if you can give us more info
