### ISSUE TITLE
Heartbeats and Endpoint registration failing with Azure Storage Queues 

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#397]
From Google Groups - https://groups.google.com/forum/#!topic/particularsoftware/U5Joyvhx2pU

In ServicePulse we see under 'Latest events'
- Endpoint 'sample' started at {Time} on host {Host}
- Endpoint sample running on host {Host} has been confirmed to have heartbeats enabled

However, no endpoints appear under 'Endpoints Overview' or 'Configuration' in ServicePulse.

Looking at the ServiceControl logs I saw the following error:

```
NServiceBus.Unicast.Transport.TransportReceiver
|Failed to process message
Raven.Abstractions.Exceptions.ConcurrencyException: PUT attempted on document 'h
eartbeats/c6827e14-1ca2-3b73-6f2e-0f6c6a7a9165' using a non current etag
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.EnsureDocumentEt
agMatch(String key, Etag etag, String method)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.AddDocument(Stri
ng key, Etag etag, RavenJObject data, RavenJObject metadata)
   at Raven.Database.DocumentDatabase.<>c__DisplayClass47.<Put>b__3f(IStorageAct
ionsAccessor actions)
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action)
   at Raven.Database.DocumentDatabase.Put(String key, Etag etag, RavenJObject do
cument, RavenJObject metadata, TransactionInformation transactionInformation)
   at Raven.Database.Extensions.CommandExtensions.Execute(ICommandData self, Doc
umentDatabase database, BatchResult batchResult)
   at Raven.Database.DocumentDatabase.ProcessBatch(IList`1 commands)
   at Raven.Database.DocumentDatabase.<>c__DisplayClass111.<Batch>b__10d(IStorag
eActionsAccessor actions)
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, Ese
ntTransactionContext transactionContext)
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action)
   at Raven.Database.DocumentDatabase.Batch(IList`1 commands)
   at Raven.Client.Embedded.EmbeddedDatabaseCommands.Batch(IEnumerable`1 command
Datas)
   at Raven.Client.Document.DocumentSession.SaveChanges()
   at ServiceControl.Infrastructure.RavenDB.RavenUnitOfWorkBehavior.Invoke(Recei
veLogicalMessageContext context, Action next) in c:\BuildAgent\work\b7f882efc2cd
360b\src\ServiceControl\Infrastructure\RavenDB\RavenUnitOfWorkBehavior.cs:line 2
6
   at NServiceBus.Pipeline.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgen
t\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 51
 at NServiceBus.Pipeline.BehaviorChain`1.Invoke(T context) in c:\BuildAgent\work
\1b05a2fea6e4cd32\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 34
   at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineA
ction, T context) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Pi
peline\PipelineExecutor.cs:line 139
   at NServiceBus.Unicast.Messages.ExecuteLogicalMessagesBehavior.Invoke(Receive
PhysicalMessageContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4c
d32\src\NServiceBus.Core\Unicast\Messages\ExecuteLogicalMessagesBehavior.cs:line
 28
   at NServiceBus.Pipeline.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgen
t\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 51
 at NServiceBus.Pipeline.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\
work\1b05a2fea6e4cd32\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 62
   at NServiceBus.UnitOfWork.UnitOfWorkBehavior.Invoke(ReceivePhysicalMessageCon
text context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBu
s.Core\UnitOfWork\UnitOfWorkBehavior.cs:line 24
```

We're using the following versions:

NServiceBus 5.0.0
NServiceBus.Azure 6.0.0
ServiceControl.Plugin.Nsb5.Heartbeat 1.0.0

ServiceControl 1.3.0
NServiceBus.Azure.Transports.WindowsAzureStorageQueues.5.3.5

he error wasn't happening every heart beat, it seemed to only be when an endpoint first started sending heartbeats?

After clearing Raven database and redeployed our NServiceBus endpoints and now they do appear in ServicePulse. Now the following exceptions are present

```
2014-10-20 06:37:57.0560|8|Error|Raven.Database.Indexing.AbstractIndexingExecuter|Failed to execute indexing
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
   at Microsoft.Isam.Esent.Interop.Update..ctor(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.UpdateLastIndexed(String index, Etag etag, DateTime timestamp)
   at Raven.Database.Indexing.IndexingExecuter.<>c__DisplayClass1b.<FilterIndexes>b__18(IStorageActionsAccessor actionsAccessor)
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext)
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action)
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action)
   at Raven.Database.Indexing.IndexingExecuter.FilterIndexes(IList`1 indexesToWorkOn, List`1 jsonDocs, Etag highestETagInBatch)
   at Raven.Database.Indexing.IndexingExecuter.DoActualIndexing(IList`1 indexesToWorkOn, List`1 jsonDocs)
   at Raven.Database.Indexing.IndexingExecuter.ExecuteIndexingWork(IList`1 indexesToWorkOn)
   at Raven.Database.Indexing.AbstractIndexingExecuter.ExecuteIndexing(Boolean isIdle, Boolean& onlyFoundIdleWork)
   at Raven.Database.Indexing.AbstractIndexingExecuter.Execute()

2014-10-21 06:05:53.2522|4|Warn|Raven.Database.Indexing.IndexSearcherHolder|Failed to properly pre-warm the facets cache (Name,Host,MessageType) for index FailedMessageFacetsIndex
System.NullReferenceException: Object reference not set to an instance of an object.
   at Raven.Database.Indexing.IndexSearcherHolder.<>c__DisplayClass4.<SetIndexSearcher>b__0()
```

**Comment by gbiellem** [comment]
@SeanFeldman   Since your looking at SC on Azure do you want to see if you can repro this?

**Comment by SeanFeldman** [comment]
@gbiellem Will do the following scenarios:
- [ ] hosting on premises with ASQ
- [ ] hosting on Azure with ASQ (multi-host)

**Comment by gbiellem** [comment]
@SeanFeldman  any update? and can you try retries - See #396

**Comment by SeanFeldman** [comment]
Have tried on-premises with ASQ, with compute emulator, and deployed to azure. Endpoint successfully registered and transmitted heartbeats. Have not tried dynamic host - on my todo list.

**Comment by SeanFeldman** [comment]
@gbiellem have confirmed that SC works fine with ASQ transport using mutlihost.
I would suggest to ask for a repro code.

**Comment by gbiellem** [comment]
@tomsave any chance you can provide some repro code as @SeanFeldman  has suggested?

**Comment by tomsave** [comment]
Just trying to upgrade to the latest nsb so we're all on the same page.

Currently getting issues upgrading Service Control / Pulse using your
installer but will keep trying.

Will let you know when I have more details

**Comment by gbiellem** [comment]
@seanfeldman any updates?

**Comment by SeanFeldman** [comment]
@gbiellem yep, it's here https://github.com/Particular/ServiceControl/issues/397#issuecomment-83090039 :)

**Comment by gbiellem** [comment]
@sean So should we close this one and track through #397? Seems odd to have both issue running

**Comment by gbiellem** [comment]
@seanfeldman So should we close this one and track through #397? Seems odd to have both issue running

**Comment by SeanFeldman** [comment]
Agree. Consolidating those is a good idea.

**Comment by SimonCropp** [comment]
@gbiellem @SeanFeldman 

> should we close this one and track through #397

but isnt this 397?

**Comment by gbiellem** [comment]
@SimonCropp oops I was off by 1.   The other issue was #396 not #397
