### ISSUE TITLE
ServiceControl stops shortly after starting

### ISSUE THREAD

**Issue by sveinfid** [Particular/ServiceControl#427]
We had a scheduled reboot last night of our production server.

It seems ServiceControl started and then stopped again after the reboot. It only ran for about 90 seconds before it stopped.

Starting it again manually works fine, though I can't seem to figure out why it stopped in the first place.

Any ideas?

Here is the only relevant entry from Application Event Log that I can find:
```
Log Name:      Application
Source:        ESENT
Date:          09.12.2014 04:31:01
Event ID:      103
Task Category: General
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      ...REMOVED...
Description:
Raven (1568) 1-4sMfg-C:\ProgramData\Particular\ServiceControl\localhost-33333\Data: The database engine stopped the instance (0).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">103</EventID>
    <Level>4</Level>
    <Task>1</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2014-12-09T03:31:01.000000000Z" />
    <EventRecordID>254001</EventRecordID>
    <Channel>Application</Channel>
    <Computer>...REMOVED...</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Raven</Data>
    <Data>1568</Data>
    <Data>1-4sMfg-C:\ProgramData\Particular\ServiceControl\localhost-33333\Data: </Data>
    <Data>0</Data>
  </EventData>
</Event>
```

Here is from the ServiceControl log file:
```
2014-12-09 04:29:31.4375|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|Using license in HKLM
2014-12-09 04:29:41.2656|7|Warn|Raven.Database.Indexing.IndexStorage.Startup|Could not open index Auto/TimeoutDatas/ByOwningTimeoutManagerAndTimeSortByTime. Recovery operation failed, forcibly resetting index
System.InvalidOperationException: Index does not exists: Auto/TimeoutDatas/ByOwningTimeoutManagerAndTimeSortByTime
   at Raven.Database.Indexing.IndexStorage.OpenOrCreateLuceneDirectory(IndexDefinition indexDefinition, String indexName, Boolean createIfMissing)
   at Raven.Database.Indexing.IndexStorage.OpenIndexOnStartup(String indexName)
2014-12-09 04:29:44.9062|4|Warn|Raven.Database.Util.PerformanceCountersManager|We could not check if the performance counter category 'RavenDB 2.0' exist or not, because it took more then the allowed timeout. We will not use the performace counter feature.
2014-12-09 04:29:44.9218|4|Warn|Raven.Database.Util.PerformanceCountersManager|Could not setup performance counters properly. Perf counters will not be used.
System.OperationCanceledException: The operation was canceled.
   at Raven.Database.Util.PerformanceCountersManager.IsValidCategory(String instanceName)
   at Raven.Database.Util.PerformanceCountersManager.Setup(String name)
2014-12-09 04:29:44.9218|12|Warn|Raven.Database.Util.PerformanceCountersManager|Could not use performance counters
2014-12-09 04:29:45.8593|4|Warn|NServiceBus.Configure|Invocation of NServiceBus.INeedInitialization completed in 14,47 s - Details:
ServiceControl.Infrastructure.RavenDB.RavenBootstrapper - 13,6186 s
Particular.ServiceControl.Licensing.LicenseDetector - 0,4971 s
NServiceBus.EnsureLoadMessageHandlersWasCalled - 0,1542 s
ServiceControl.Infrastructure.SignalR.Configure - 0,0887 s
ServiceControl.BusinessMonitoring.EndpointSLAMonitoring - 0,0243 s
NServiceBus.Licensing.LicenseInitializer - 0,0216 s
NServiceBus.Unicast.Transport.Config.Bootstrapper - 0,0088 s
ServiceControl.EndpointControl.Handlers.KnownEndpointsCache - 0,0059 s
NServiceBus.Unicast.Queuing.QueuesCreator - 0,0056 s
ServiceControl.Operations.ImportRegistration - 0,0041 s
ServiceControl.CustomChecks.CustomCheckNotifications - 0,0039 s
NServiceBus.Pipeline.PipelineOverrideConfigurer - 0,0035 s
ServiceControl.EventLog.EventLogMappings - 0,0034 s
NServiceBus.Config.SatelliteConfigurer - 0,0032 s
NServiceBus.Scheduling.Configuration.SchedulerConfiguration - 0,0029 s
NServiceBus.Unicast.Config.StartupRunners - 0,0026 s
ServiceControl.MessageFailures.FailedMessageViewIndexNotifications - 0,0026 s
ServiceControl.HeartbeatMonitoring.HeartbeatStatusInitializer - 0,0025 s
ServiceControl.Operations.LicenseStatusKeeper - 0,0016 s
ServiceControl.ExternalIntegrations.ExternalIntegrationsInitializer - 0,0012 s
NServiceBus.Unicast.Monitoring.VersionMutator - 0,0011 s
NServiceBus.Unicast.Monitoring.CausationMutator - 0,0011 s
NServiceBus.Unicast.BackwardCompatibility.MutateMessageContentTypeOfIncomingTransportMessages - 0,0011 s
NServiceBus.Unicast.Monitoring.ProcessingStatistics - 0,0011 s
NServiceBus.Unicast.BackwardCompatibility.SetIsSagaMessageHeaderForV3XMessages - 0,0011 s
NServiceBus.Gateway.HeaderManagement.GatewayHeaderManager - 0,0011 s
NServiceBus.Encryption.Bootstrapper - 0,0011 s
NServiceBus.Bootstrapper - 0,0009 s
NServiceBus.Audit.InitMessageAuditer - 0,0007 s
NServiceBus.Sagas.AutoCorrelateSagaOnReplyMutator - 0,0004 s
NServiceBus.Sagas.OriginatingSagaHeaderMutator - 0,0003 s

2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2014-12-09 04:31:01.3906|1|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
```

PS: We are using ServiceControl 1.4.2

**Comment by gbiellem** [comment]
@sveinfid  At this stage we've not been able to repro. Will keep the issue open.  
Do you have anything more for us to go on? And is it still occurring?

**Comment by fredricadell** [comment]
We are experiencing the same problem with version 1.4.3 in our test and acceptancetest environment. The Servicecontrol service starts and then stops after ca 90 seconds.. This is from our log in acceptancetest:

2015-01-13 16:29:14.1596|34|Error|ServiceControl.ExternalIntegrations.EventDispatcher|An exception occurred when dispatching external integration events
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at ServiceControl.ExternalIntegrations.MessageFailedConverter.ToEvent(FailedMessage message) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\MessageFailedConverter.cs:line 16
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEventBatch(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 86
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEvents(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 60
   at ServiceControl.ExternalIntegrations.EventDispatcher.<StartDispatcher>b__4() in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 33
   at System.Threading.Tasks.Task.Execute()
2015-01-13 16:29:34.0504|7|Warn|NServiceBus.CircuitBreakers.RepeatedFailuresOverTimeCircuitBreaker|The circuit breaker for EventDispatcher will now be triggered
2015-01-13 16:29:34.0504|7|Fatal|NServiceBus|Repeated failures when dispatching external integration events.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at ServiceControl.ExternalIntegrations.MessageFailedConverter.ToEvent(FailedMessage message) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\MessageFailedConverter.cs:line 16
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEventBatch(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 86
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEvents(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 60
   at ServiceControl.ExternalIntegrations.EventDispatcher.<StartDispatcher>b__4() in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 33
   at System.Threading.Tasks.Task.Execute()
2015-01-13 16:29:35.0817|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1129|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1129|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1286|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1442|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1442|7|Warn|Raven.Storage.Esent.StorageActions.DocumentStorageActions|Error when trying to open a new DocumentStorageActions
Microsoft.Isam.Esent.Interop.EsentInvalidInstanceException: Invalid instance handle
   at Microsoft.Isam.Esent.Interop.Session..ctor(JET_INSTANCE instance)
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions..ctor(JET_INSTANCE instance, String database, TableColumnsCache tableColumnsCache, OrderedPartCollection`1 documentCodecs, IUuidGenerator uuidGenerator, IDocumentCacher cacher, EsentTransactionContext transactionContext, TransactionalStorage transactionalStorage)
2015-01-13 16:29:35.1442|34|Warn|Raven.Database.Indexing.IndexSearcherHolder|Failed to properly pre-warm the facets cache (Name) for index FailedMessageFacetsIndex
System.NullReferenceException: Object reference not set to an instance of an object.
   at Raven.Database.Indexing.IndexSearcherHolder.<>c__DisplayClass4.<SetIndexSearcher>b__0()

**Comment by fredricadell** [comment]
And also this.. 

2015-01-13 16:39:37.3528|5|Error|ServiceControl.ExternalIntegrations.EventDispatcher|An exception occurred when dispatching external integration events
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at ServiceControl.ExternalIntegrations.MessageFailedConverter.ToEvent(FailedMessage message) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\MessageFailedConverter.cs:line 16
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEventBatch(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 86
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEvents(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 60
   at ServiceControl.ExternalIntegrations.EventDispatcher.<StartDispatcher>b__4() in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 33
   at System.Threading.Tasks.Task.Execute()
2015-01-13 16:39:57.4311|10|Error|ServiceControl.ExternalIntegrations.EventDispatcher|An exception occurred when dispatching external integration events
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at ServiceControl.ExternalIntegrations.MessageFailedConverter.ToEvent(FailedMessage message) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\MessageFailedConverter.cs:line 16
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEventBatch(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 86
   at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEvents(CancellationToken token) in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 60
   at ServiceControl.ExternalIntegrations.EventDispatcher.<StartDispatcher>b__4() in c:\BuildAgent\work\b7f882efc2cd360b\src\ServiceControl\ExternalIntegrations\EventDispatcher.cs:line 33
   at System.Threading.Tasks.Task.Execute()

**Comment by synhershko** [comment]
@fredricadell is this reproducible?

**Comment by gbiellem** [comment]
Hi @synhershko 

Yes it is - there is a support  case related to it here - https://nservicebus.desk.com/agent/case/8621
We are working on a fix now.

**Comment by gbiellem** [comment]
Fixed in https://github.com/Particular/ServiceControl/commit/0764fefa62f2276bedba3a7929f1d91d8851b256
