### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#448]
Reported against v1.1

Initial reported in [mailing list](https://groups.google.com/d/msg/particularsoftware/VZVvZRSIMHE/TrQyT9WpjA4J) - System.InvalidOperationException: Sequence contains more than one matching element

### Symptoms
```
2015-02-13 16:29:19.7706|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|Using license in current folder (C:\Program Files (x86)\Particular Software\ServiceControl\License\License.xml).
2015-02-13 16:29:25.1731|26|Fatal|NServiceBus|ServiceControl.HeartbeatMonitoring.HeartbeatStatusInitializer, ServiceControl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null could not be started.
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ServiceControl.HeartbeatMonitoring.HeartbeatStatusProvider.TryFindEndpoint(EndpointDetails endpointDetails) in c:\BuildAgent\work\2c4c51d06662248c\src\ServiceControl\HeartbeatMonitoring\HeartbeatStatusProvider.cs:line 144
   at ServiceControl.HeartbeatMonitoring.HeartbeatStatusProvider.GetEndpoint(EndpointDetails endpointDetails) in c:\BuildAgent\work\2c4c51d06662248c\src\ServiceControl\HeartbeatMonitoring\HeartbeatStatusProvider.cs:line 117
   at ServiceControl.HeartbeatMonitoring.HeartbeatStatusProvider.RegisterNewEndpoint(EndpointDetails endpointDetails) in c:\BuildAgent\work\2c4c51d06662248c\src\ServiceControl\HeartbeatMonitoring\HeartbeatStatusProvider.cs:line 16
   at ServiceControl.HeartbeatMonitoring.HeartbeatStatusInitializer.<Initialise>b__1(IEnumerable`1 endpoints) in c:\BuildAgent\work\2c4c51d06662248c\src\ServiceControl\HeartbeatMonitoring\HeartbeatStatusInitializer.cs:line 56
   at Raven.Client.Document.DocumentSession.ExecuteAllPendingLazyOperations()
   at ServiceControl.HeartbeatMonitoring.HeartbeatStatusInitializer.Initialise() in c:\BuildAgent\work\2c4c51d06662248c\src\ServiceControl\HeartbeatMonitoring\HeartbeatStatusInitializer.cs:line 84
   at NServiceBus.Unicast.UnicastBus.<>c__DisplayClass1b.<Start>b__19() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 863
```

### Who is affected
Anyone that is currently seeing the above exception at startup

**Comment by antonyfrancis** [comment]
This error happening in the v1.5 as well

**Comment by johnsimons** [comment]
@antonyfrancis what version of AzureServiceBusQueue are you using ?

**Comment by johnsimons** [comment]
@antonyfrancis what versions of NServiceBus are your endpoints using ?

**Comment by johnsimons** [comment]
After reviewing some of the code involved in registering endpoints, the following highlighted code seems buggy to me, https://github.com/Particular/ServiceControl/blob/ea2d5bc073fab378fc3d70cab5b77afc8837f976/src/ServiceControl/EndpointControl/Handlers/RegisterEndpointHandler.cs#L75-L85, thoughts @Particular/servicecontrol  ?

**Comment by SzymonPobiega** [comment]
Yeah. I wonder what RavenDB does if a session wants to both delete and store a document..
