### ISSUE TITLE
Failure at start in develop

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#458]
```
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at Raven.Client.Embedded.EmbeddedDatabaseCommands.<YieldUntilDone>d__32.<>m__Finally34()
       at Raven.Client.Embedded.EmbeddedDatabaseCommands.<YieldUntilDone>d__32.MoveNext()
       at Raven.Client.Document.DocumentSession.<YieldQuery>d__c`1.MoveNext()
       at ServiceControl.Operations.AttemptToReImportFailedMessages.Run[T,I](CancellationToken token) in c:\Projects\ServiceControl\src\Particular.Backend.AuditIngestion\AttemptToReImportFailedMessages.cs:line 39
       at ServiceControl.Operations.AttemptToReImportFailedMessages.<Start>b__0() in c:\Projects\ServiceControl\src\Particular.Backend.AuditIngestion\AttemptToReImportFailedMessages.cs:line 22
       at System.Threading.Tasks.Task.Execute()
  InnerException: Raven.Abstractions.Exceptions.IndexDoesNotExistsException
       HResult=-2146233088
       Message=Could not find index named: FailedErrorImportIndex
       Source=Raven.Database
       StackTrace:
            at Raven.Database.DocumentDatabase.<>c__DisplayClass8f.<Query>b__84(IStorageActionsAccessor actions)
            at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext)
            at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action)
            at Raven.Database.DocumentDatabase.Query(String index, IndexQuery query, CancellationToken externalCancellationToken, Action`1 headerInfo, Action`1 onResult)
            at Raven.Client.Embedded.EmbeddedDatabaseCommands.<>c__DisplayClass27.<StreamQuery>b__21()
            at System.Threading.Tasks.Task.Execute()
       InnerException: 

```

**Comment by johnsimons** [comment]
Fixed
