### ISSUE TITLE
Exception thrown during shutdown

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#481]
Using develop branch

```
Exception thrown during shutdown 

System.ObjectDisposedException was unhandled by user code
  HResult=-2146232798
  Message=Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
  Source=Autofac
  ObjectName=""
  StackTrace:
       at Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed()
       at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
       at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
       at NServiceBus.ObjectBuilder.Autofac.AutofacObjectBuilder.Build(Type typeToBuild) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\ObjectBuilder\Autofac\AutofacObjectBuilder.cs:line 57
       at NServiceBus.ObjectBuilder.Common.CommonObjectBuilder.Build[T]() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs:line 159
       at NServiceBus.Unicast.UnicastBus.get_LogicalMessageFactory() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 1220
       at NServiceBus.Unicast.UnicastBus.Publish[T](T[] messages) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 321
       at NServiceBus.Unicast.UnicastBus.Publish[T](T message) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 294
       at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEventBatch(CancellationToken token) in c:\Projects\ServiceControl\src\ServiceControl.Core\ExternalIntegrations\EventDispatcher.cs:line 92
       at ServiceControl.ExternalIntegrations.EventDispatcher.DispatchEvents(CancellationToken token) in c:\Projects\ServiceControl\src\ServiceControl.Core\ExternalIntegrations\EventDispatcher.cs:line 60
       at ServiceControl.ExternalIntegrations.EventDispatcher.<StartDispatcher>b__4() in c:\Projects\ServiceControl\src\ServiceControl.Core\ExternalIntegrations\EventDispatcher.cs:line 33
       at System.Threading.Tasks.Task.Execute()
  InnerException: 

```

**Comment by johnsimons** [comment]
@danielmarbach do u want to have a look at this one ?

**Comment by johnsimons** [comment]
develop was rolledback
