### ISSUE TITLE
Problem upgrading when database not shutdown cleanly

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceControl#499]
I was trying to upgrade to 1.6.1 and getting some obscure error messages. Uninstall and fresh install did not work either. Managed to trace it down to when it's executing the service install, and invoked it manually to see what was going on.  Apparently the database wasn't shutdown cleanly. I don't care about this database (dev) so I simply removed the folder and reinstalled, which worked fine.

Hopefully this could be trapped better, making it easier to understand what is going on.

Unhandled Exception: System.InvalidOperationException: Could not open transactional storage: C:\ProgramData\Particular\ServiceControl\localhost-33333\Data ---> Microsoft.Isam.Esent.Interop.EsentDatabaseDirtyShutdownException: Database was not shutdown cleanly. Recovery must first be run to properly complete database operations for the previous shutdown.
   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err)
   at Microsoft.Isam.Esent.Interop.Api.JetAttachDatabase2(JET_SESID sesid, String database, Int32 maxPages, AttachDatabaseGrbit grbit)
   at Raven.Storage.Esent.TransactionalStorage.EnsureDatabaseIsCreatedAndAttachToDatabase()
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs)
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs)
   at Raven.Database.DocumentDatabase..ctor(InMemoryRavenConfiguration configuration, TransportState transportState)
   at Raven.Client.Embedded.EmbeddableDocumentStore.InitializeInternal()
   at Raven.Client.Document.DocumentStore.Initialize()
   at ServiceControl.Infrastructure.RavenDB.RavenBootstrapper.Init() in c:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\RavenDB\RavenBootstrapper.cs:line 70
   at NServiceBus.Configure.<>c__DisplayClass23`1.<ActivateAndInvoke>b__20(Type t) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Configure.cs:line 556
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at NServiceBus.Configure.ActivateAndInvoke[T](Action`1 action, Nullable`1 thresholdForWarning) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Configure.cs:line 561
   at NServiceBus.Configure.Initialize() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Configure.cs:line 352
   at NServiceBus.Configure.CreateBus() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Configure.cs:line 295
   at Particular.ServiceControl.Bootstrapper..ctor(ServiceBase host, HostArguments hostArguments, Configure configure) in c:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Bootstrapper.cs:line 53
   at Particular.ServiceControl.Commands.RunBootstrapperAndNServiceBusInstallers.Execute(HostArguments args) in c:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Hosting\Commands\RunBootstrapperAndNServiceBusInstallers.cs:line 13
   at Particular.ServiceControl.Commands.CommandRunner.Execute(HostArguments args) in c:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Hosting\Commands\CommandRunner.cs:line 16
   at Particular.ServiceControl.Program.Main(String[] args) in c:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Program.cs:line 24

**Comment by johnsimons** [comment]
@gbiellem @mikeminutillo any ideas how we can improve this situation ?

**Comment by johnsimons** [comment]
It looks like the recomendation is to run `esentutl /p <databasename>`, see https://groups.google.com/d/msg/ravendb/eKUYf2cHUkQ/EoRxiRX2YUUJ

Should we document this ?

**Comment by mikeminutillo** [comment]
On the [Esent Repair](https://technet.microsoft.com/en-us/library/hh875504.aspx) page it also explicityly recommends running an [Esent Recovery](https://technet.microsoft.com/en-us/library/hh875590.aspx) first for databases in the "dirty shutdown" state.

Adding this to the troubleshooting docs page.

**Comment by johnsimons** [comment]
This is now documented, see http://docs.particular.net/servicecontrol/troubleshooting#service-fails-to-start-esentdatabasedirtyshutdownexception
