### ISSUE TITLE
A null reference exception is raised when a retry is issued for a non existing failuremessage id

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#589]
### Who's affected
Users that retry a failed message with an invalid id

### Symptoms
A null reference exception is raised on high retries concurrency scenarios.
Exception thrown:
```
2015-11-10 09:35:46.5824|92|Error|ServiceControl.Recoverability.FailedMessageRetries+ProcessRetryBatches|Error during retry batch processing
System.NullReferenceException: Object reference not set to an instance of an object.
at ServiceControl.Recoverability.RetryProcessor.StageMessage(FailedMessage message, String stagingId) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retries\RetryProcessor.cs:line 141
at ServiceControl.Recoverability.RetryProcessor.Stage(RetryBatch stagingBatch, IDocumentSession session) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retries\RetryProcessor.cs:line 122
at ServiceControl.Recoverability.RetryProcessor.ProcessBatches(IDocumentSession session) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retries\RetryProcessor.cs:line 64
at ServiceControl.Recoverability.FailedMessageRetries.ProcessRetryBatches.Process(PeriodicExecutor e) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retries\FailedMessageRetries.cs:line 130
at ServiceControl.Infrastructure.PeriodicExecutor.<>c__DisplayClass7_0.<<Start>b__0>d.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\PeriodicExecutor.cs:line 53
```

**Comment by johnsimons** [comment]
@mikeminutillo can u review the fix and suggest a way to test this ?

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl/commit/d079110fb86bddf299eccddb38ead9cfeedf3211
