### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.JsonSerializerSettings' to type 'Microsoft.AspNet.SignalR.Json.IJsonSerializer'.

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#631]
Customer log file on v1.8.3 contains the following exception:

```
13:03:47.7036|17|Info|NServiceBus.Unicast.Transport.TransportReceiver|Failed to process message
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.JsonSerializerSettings' to type 'Microsoft.AspNet.SignalR.Json.IJsonSerializer'.
   at Microsoft.AspNet.SignalR.DependencyResolverExtensions.Resolve[T](IDependencyResolver resolver)
   at Microsoft.AspNet.SignalR.Infrastructure.ConnectionManager.GetConnectionCore(String connectionName)
   at Microsoft.AspNet.SignalR.Infrastructure.ConnectionManager.GetConnection(Type type)
   at ServiceControl.Infrastructure.SignalR.GlobalEventHandler.Handle(IEvent event) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\SignalR\GlobalEventHandler.cs:line 17
   at NServiceBus.Unicast.MessageHandlerRegistry.Invoke(Object handler, Object message, Dictionary`2 dictionary) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\MessageHandlerRegistry.cs:line 124
   at NServiceBus.InvokeHandlersBehavior.Invoke(IncomingContext context, Action next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\InvokeHandlersBehavior.cs:line 23
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 107
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.SetCurrentMessageBeingHandledBehavior.Invoke(IncomingContext context, Action next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\SetCurrentMessageBeingHandledBehavior.cs:line 17
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 107
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.LoadHandlersBehavior.Invoke(IncomingContext context, Action next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\LoadHandlersBehavior.cs:line 45
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 107
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
```

**Comment by johnsimons** [comment]
At this point have no idea how to repro it

**Comment by johnsimons** [comment]
This is fixed in later versions, it was a timing issue
