### ISSUE TITLE
database queue schemas are not supported

### ISSUE THREAD

**Issue by rlaveycal** [Particular/ServiceControl#692]
Despite #459 being closed and the issue stating that this was fixed in release 1.7.0 I cannot get service control to start when configured to use a DB schema for my queues. I'm using 1.11.1

The config is
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <appSettings>
        <add key="ServiceControl/LogLevel" value="info" />
        <add key="ServiceControl/Port" value="33333" />
        <add key="ServiceControl/HostName" value="localhost" />
        <add key="ServiceControl/LogPath" value="C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl\Logs" />
        <add key="ServiceControl/DBPath" value="C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl\DB" />
        <add key="ServiceControl/ForwardAuditMessages" value="False" />
        <add key="ServiceControl/TransportType" value="NServiceBus.SqlServerTransport, NServiceBus.Transports.SQLServer" />
        <add key="ServiceBus/AuditQueue" value="bus.audit" />
        <add key="ServiceBus/ErrorQueue" value="bus.error" />
        <add key="ServiceBus/ErrorLogQueue" value="bus.error.log" />
        <add key="ServiceBus/AuditLogQueue" value="bus.audit.log" />
        <add key="Raven/Esent/MaxVerPages" value="2048" />
    </appSettings>
    <connectionStrings>
        <add name="NServiceBus/Transport" connectionString="server=localhost;database=ctn_servicebus;integrated security=true" />
    </connectionStrings>
    <runtime>
        <gcServer enabled="true" />
    </runtime>
</configuration>
```

The log file contains
```
2016-03-11 14:26:31.8443|4|Warn|NServiceBus.Transports.SQLServer.TableBasedQueue|Table [dbo].[bus.error] does not contain index 'Index_Expires'.

2016-03-11 14:26:31.8323|12|Warn|NServiceBus.Transports.SQLServer.SqlServerPollingDequeueStrategy|An exception occurred when connecting to the configured SQLServer instance
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.bus.audit'.

2016-03-11 14:26:31.9443|5|Fatal|NServiceBus|Error Import cannot start
NServiceBus.Unicast.Queuing.QueueNotFoundException: Failed to send message to address: [bus.error.log] ---> System.Data.SqlClient.SqlException: Invalid object name 'dbo.bus.error.log'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NServiceBus.Transports.SQLServer.TableBasedQueue.Send(Object[] messageData, SqlConnection connection, SqlTransaction transaction) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 42
   at NServiceBus.Transports.SQLServer.SqlServerMessageSender.Send(TransportMessage message, SendOptions sendOptions) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\SqlServerMessageSender.cs:line 51
   --- End of inner exception stack trace ---
   at NServiceBus.Transports.SQLServer.SqlServerMessageSender.ThrowQueueNotFoundException(Address destination, SqlException ex) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\SqlServerMessageSender.cs:line 91
   at NServiceBus.Transports.SQLServer.SqlServerMessageSender.Send(TransportMessage message, SendOptions sendOptions) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\SqlServerMessageSender.cs:line 77
   at ServiceControl.Operations.ErrorQueueImport.TerminateIfForwardingQueueNotWritable() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\ErrorQueueImport.cs:line 116

```

Please help!

**Comment by mikeminutillo** [comment]
Hi @rlaveycal, 

I believe that you can fix this by adding `Queue Schema=bus` to your connection string and dropping the schema name from the queue names in your configuration. It will look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <appSettings>
        <add key="ServiceControl/LogLevel" value="info" />
        <add key="ServiceControl/Port" value="33333" />
        <add key="ServiceControl/HostName" value="localhost" />
        <add key="ServiceControl/LogPath" value="C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl\Logs" />
        <add key="ServiceControl/DBPath" value="C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl\DB" />
        <add key="ServiceControl/ForwardAuditMessages" value="False" />
        <add key="ServiceControl/TransportType" value="NServiceBus.SqlServerTransport, NServiceBus.Transports.SQLServer" />
        <add key="ServiceBus/AuditQueue" value="audit" />
        <add key="ServiceBus/ErrorQueue" value="error" />
        <add key="ServiceBus/ErrorLogQueue" value="error.log" />
        <add key="ServiceBus/AuditLogQueue" value="audit.log" />
        <add key="Raven/Esent/MaxVerPages" value="2048" />
    </appSettings>
    <connectionStrings>
        <add name="NServiceBus/Transport" connectionString="server=localhost;database=ctn_servicebus;integrated security=true; Queue Schema=bus" />
    </connectionStrings>
    <runtime>
        <gcServer enabled="true" />
    </runtime>
</configuration>
```

I'm setting up SC with SQL Transport now to confirm.

**Comment by mikeminutillo** [comment]
OK. I have run this in my test environment and it works.

@rlaveycal If this solves your problem, please let me know and I will close this issue.

**Comment by rlaveycal** [comment]
Thanks. This works _if_ I pre-create the tables required by service control.

**Comment by johnsimons** [comment]
@rlaveycal the tables creation should use the supplied schema as long as the schema already exists

**Comment by mikeminutillo** [comment]
I am closing this one.

@rlaveycal let me know if this is an ongoing issue and I'll re-open it.
