### ISSUE TITLE
Exception when retrying hundreds of thousands messages

### ISSUE THREAD

**Issue by pablocastilla** [Particular/ServiceControl#700]
Hi!

I am trying to retry lots of messages. It fails after a while with this exception:

2016-03-17 08:14:34.7309|22|Error|Raven.Database.Indexing.AbstractIndexingExecuter|Failed to execute indexing

Microsoft.Isam.Esent.Interop.EsentVersionStoreOutOfMemoryException: Version store out of memory (cleanup already attempted)

   at Microsoft.Isam.Esent.Interop.Update..ctor(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Update.cs:line 44

   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.UpdateLastIndexed(String index, Etag etag, DateTime timestamp) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\Indexing.cs:line 233

   at Raven.Database.Indexing.IndexingExecuter.<>c__DisplayClass1b.<FilterIndexes>b__18(IStorageActionsAccessor actionsAccessor) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexingExecuter.cs:line 298

   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 703

   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 682

   at Raven.Database.Indexing.IndexingExecuter.FilterIndexes(IList`1 indexesToWorkOn, List`1 jsonDocs, Etag highestETagInBatch) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexingExecuter.cs:line 302

   at Raven.Database.Indexing.IndexingExecuter.DoActualIndexing(IList`1 indexesToWorkOn, List`1 jsonDocs) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexingExecuter.cs:line 159

   at Raven.Database.Indexing.IndexingExecuter.ExecuteIndexingWork(IList`1 indexesToWorkOn) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\IndexingExecuter.cs:line 131

   at Raven.Database.Indexing.AbstractIndexingExecuter.ExecuteIndexing(Boolean isIdle, Boolean& onlyFoundIdleWork) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\AbstractIndexingExecuter.cs:line 237

   at Raven.Database.Indexing.AbstractIndexingExecuter.Execute() in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\AbstractIndexingExecuter.cs:line 46

**Comment by gbiellem** [comment]
@pablocastilla  what version of ServiceControl are you using?

**Comment by pablocastilla** [comment]
The version is 1.7.6.

I think I have fixed the problem with the following configuration:
<add key="Raven/Esent/CacheSizeMax" value="1024"/>
<add key="Raven/Esent/MaxVerPages" value="2048"/>

But not totally sure until next massive retry.

**Comment by johnsimons** [comment]
@pablocastilla  We have recently addressed quite a few issues regarding tuning of queries against RavenDB, would it be possible for you to update to latest 1.11.1 ?
It is important to stay up to date because we are constantly making small improvements on this product.

**Comment by pablocastilla** [comment]
I will upgrade and tell you if it keep falling.

Thanks

**Comment by johnsimons** [comment]
@pablocastilla how is this going ? Is it working now ? Can we close this ?

**Comment by pablocastilla** [comment]
Works perfect! :)

Close it
