### ISSUE TITLE
Error messages list do not include time of failure

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#703]
We return the time of failure to all /api/errors api calls.
```json
"time_of_failure": "2016-03-22T06:25:16.021602Z",
```
We also now support sorting by time_of_failure, eg:
`http://localhost:33333/api/errors/?sort=time_of_failure&status=Archived`

**Comment by johnsimons** [comment]
@petersgiles as discussed

**Comment by petersgiles** [comment]
@johnsimons getting this error with your latest after changing to `time_of_failure`

http://localhost:33333/api/recoverability/groups/b61236bf-b997-04e4-f2c0-5b40acc2e281/errors?page=1&sort=time_of_failure

``` C#
Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentException: The field 'TimeOfFailure' is not indexed, cannot sort on fields that are not indexed
   at Raven.Database.Indexing.Index.AssertQueryDoesNotContainFieldsThatAreNotIndexed(IndexQuery indexQuery, AbstractViewGenerator viewGenerator) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\Index.cs:line 901
   at Raven.Database.Indexing.Index.IndexQueryOperation.d__57.MoveNext() in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Indexing\Index.cs:line 971
   at Raven.Database.Util.ActiveEnumerable`1..ctor(IEnumerable`1 enumerable) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Util\ActiveEnumerable.cs:line 16
   at Raven.Database.DocumentDatabase.<>c__DisplayClass97.b__8c(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1376
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 712
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 656
   at Raven.Database.DocumentDatabase.Query(String index, IndexQuery query, CancellationToken externalCancellationToken, Action`1 headerInfo, Action`1 onResult) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1416
   at Raven.Database.DocumentDatabase.Query(String index, IndexQuery query, CancellationToken token) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1312
   at Raven.Client.Embedded.EmbeddedDatabaseCommands.Query(String index, IndexQuery query, String[] includes, Boolean metadataOnly, Boolean indexEntriesOnly) in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Embedded\EmbeddedDatabaseCommands.cs:line 486
   at Raven.Client.Document.AbstractDocumentQuery`2.ExecuteActualQuery() in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Lightweight\Document\AbstractDocumentQuery.cs:line 680
   at Raven.Client.Document.AbstractDocumentQuery`2.GetEnumerator() in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Lightweight\Document\AbstractDocumentQuery.cs:line 904
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ServiceControl.Recoverability.FailureGroupsApi.GetGroupErrors(String groupId) in C:\Code\ServiceControl\src\ServiceControl\Recoverability\Grouping\FailureGroupsApi.cs:line 64
   at ServiceControl.Recoverability.FailureGroupsApi.<.ctor>b__4_2(Object parameters) in C:\Code\ServiceControl\src\ServiceControl\Recoverability\Grouping\FailureGroupsApi.cs:line 28
   at Nancy.Routing.Route.<>c__DisplayClass4.b__3(Object parameters, CancellationToken context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```
