### ISSUE TITLE
ServiceControl crashes on startup if audit.log queue is full

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#739]
## Who's affected

* Any user using audit forwarding where the audit forwarding queue is full

## Symptoms

ServiceControl will not start up correctly if the audit queue is full and will not provide the user with any meaningful feedback other than `Failed to stop service. System.ObjectDisposedException: The CancellationTokenSource has been disposed.` in the event log.

## Stacktrace from user

This stacktrace is at ServiceControl startup from within the log file.

```
System.Exception: Failed to send message to address: audit.log@MACHINENAME ---> System.Messaging.MessageQueueException: Insufficient resources to perform operation.
   at System.Messaging.MessageQueue.SendInternal(Object obj, MessageQueueTransaction internalTransaction, MessageQueueTransactionType transactionType)
   at NServiceBus.Transports.Msmq.MsmqMessageSender.Send(TransportMessage message, SendOptions sendOptions) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqMessageSender.cs:line 67
   --- End of inner exception stack trace ---
   at NServiceBus.Transports.Msmq.MsmqMessageSender.ThrowFailedToSendException(Address address, Exception ex) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqMessageSender.cs:line 103
   at NServiceBus.Transports.Msmq.MsmqMessageSender.Send(TransportMessage message, SendOptions sendOptions) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqMessageSender.cs:line 83
   at ServiceControl.Operations.AuditQueueImport.TerminateIfForwardingIsEnabledButQueueNotWritable() in C:\Build\src\ServiceControl\Operations\AuditQueueImport.cs:line 98
2016-06-01 09:04:12.6868|19|Fatal|NServiceBus|Startup task failed to complete.
```

**Comment by johnsimons** [comment]
@WilliamBZA this seems to work as expected.
If we can't write to the queue we assume is not safe to proceed, and notify the user by "shutting down".

Regarding the error, I am not sure we can do much better, MSMQ errors are not granular enough to tell exactly what is wrong.

Not too sure how to proceed here? @Particular/servicecontrol-maintainers  thoughts ?

**Comment by johnsimons** [comment]
@WilliamBZA what version of ServiceControl ?

**Comment by WilliamBZA** [comment]
`1.16.0`

Something else appears to be the issue here. Closing this until I have a proper repro.
