### ISSUE TITLE
ServiceControl memory leak

### ISSUE THREAD

**Issue by kye** [Particular/ServiceControl#798]
We use ServiceControl to monitor around 10 nodes all looking at a single nServiceBus SQL database. We noticed ServicePulse timing out so we checked the ServiceControl windows service. The service was using 7GB worth of memory. We restarted the service and were able to see failed messages again - but within a few minutes the memory increased and the service was unresponsive.

I cannot see anything helpful in the log files to suggest the source of the problem or anything relevant on https://docs.particular.net/servicecontrol/troubleshooting. 

I'd like to keep the existing failed messages, but I'm happy for everything else to removed. Or if my only option is to reinstall - so be it.

Could you please advise if there is anything I should check/do to correct the problem?

Thank you

 
```
-------------------------------------------------------------
ServiceControl Version:				1.23.0.0
Selected Transport:					NServiceBus.SqlServerTransport, NServiceBus.Transports.SQLServer
Audit Retention Period:				30.00:00:00
Error Retention Period:				15.00:00:00
Forwarding Error Messages:		False
Forwarding Audit Messages:		False
Database Size:							16795639808bytes
-------------------------------------------------------------
2016-10-05 12:47:57.8900|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License found at 'HKEY_LOCAL_MACHINE\SOFTWARE\ParticularSoftware'
2016-10-05 12:47:57.9056|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License not found in D:\FOO.ServiceControl\Bin\License\License.xml
2016-10-05 12:47:57.9056|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License not found in D:\FOO.ServiceControl\Bin\ParticularPlatformLicense.xml
2016-10-05 12:47:57.9056|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|Selected active license from HKEY_LOCAL_MACHINE\SOFTWARE\ParticularSoftware
2016-10-05 12:47:57.9056|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License Expiration: 13 November 2016
2016-10-05 12:47:59.3252|4|Warn|NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper|Interface ICustomAttributeProvider contains methods and can there for not be mapped. Be aware that non mapped interface can't be used to send messages.
2016-10-05 12:47:59.8868|4|Warn|NServiceBus.Transports.SQLServer.TableBasedQueue|Table [dbo].[FOO.ServiceControl] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-10-05 12:47:59.9336|4|Warn|NServiceBus.Transports.SQLServer.TableBasedQueue|Table [dbo].[error] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-10-05 12:47:59.9336|13|Warn|NServiceBus.Transports.SQLServer.TableBasedQueue|Table [dbo].[audit] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-10-05 13:16:03.2120|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License found at 'HKEY_LOCAL_MACHINE\SOFTWARE\ParticularSoftware'
2016-10-05 13:16:03.2120|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License not found in D:\FOO.ServiceControl\Bin\License\License.xml
2016-10-05 13:16:03.2120|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License not found in D:\FOO.ServiceControl\Bin\ParticularPlatformLicense.xml
2016-10-05 13:16:03.2120|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|Selected active license from HKEY_LOCAL_MACHINE\SOFTWARE\ParticularSoftware
2016-10-05 13:16:03.2120|4|Info|Particular.ServiceControl.Licensing.LicenseDetector|License Expiration: 13 November 2016
2016-10-05 13:16:04.6784|4|Warn|NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper|Interface ICustomAttributeProvider contains methods and can there for not be mapped. Be aware that non mapped interface can't be used to send messages.
2016-10-05 13:16:05.2868|4|Warn|NServiceBus.Transports.SQLServer.TableBasedQueue|Table [dbo].[FOO.ServiceControl] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-10-05 13:16:05.3180|4|Warn|NServiceBus.Transports.SQLServer.TableBasedQueue|Table [dbo].[error] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-10-05 13:16:05.3180|4|Warn|NServiceBus.Transports.SQLServer.TableBasedQueue|Table [dbo].[audit] does not contain index 'Index_Expires'.
Adding this index will speed up the process of purging expired messages from the queue. Please consult the documentation for further information.
2016-10-05 14:40:47.8985|56|Warn|NServiceBus.Transports.SQLServer.ExpiredMessagesPurger|Purging expired messages from table [dbo].[FOO.ServiceControl] failed after purging 0 messages. Exception: System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NServiceBus.Transports.SQLServer.TableBasedQueue.PurgeBatchOfExpiredMessages(SqlConnection connection, Int32 purgeBatchSize) in C:\Build\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 201
   at NServiceBus.Transports.SQLServer.ExpiredMessagesPurger.PurgeExpiredMessages() in C:\Build\src\NServiceBus.SqlServer\ExpiredMessagesPurger.cs:line 92
ClientConnectionId:52fa6b89-a0d4-46f9-bbb9-3b63d8ac3e27
Error Number:-2,State:0,Class:11
2016-10-05 16:56:14.8346|77|Warn|NServiceBus.Transports.SQLServer.ExpiredMessagesPurger|Purging expired messages from table [dbo].[FOO.ServiceControl] failed after purging 0 messages. Exception: System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NServiceBus.Transports.SQLServer.TableBasedQueue.PurgeBatchOfExpiredMessages(SqlConnection connection, Int32 purgeBatchSize) in C:\Build\src\NServiceBus.SqlServer\TableBasedQueue.cs:line 201
   at NServiceBus.Transports.SQLServer.ExpiredMessagesPurger.PurgeExpiredMessages() in C:\Build\src\NServiceBus.SqlServer\ExpiredMessagesPurger.cs:line 92
ClientConnectionId:d670a3cc-9c2b-478b-8f23-c4b0384ab9ae
Error Number:-2,State:0,Class:11
2016-10-05 19:35:36.8490|25|Error|ServiceBus.Management.Infrastructure.Nancy.NServiceBusContainerBootstrapper|Http call failed
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Raven.Database.DocumentDatabase.<>c__DisplayClass97.<Query>b__8c(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1404
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 712
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 656
   at Raven.Database.DocumentDatabase.Query(String index, IndexQuery query, CancellationToken externalCancellationToken, Action`1 headerInfo, Action`1 onResult) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1416
   at Raven.Database.DocumentDatabase.Query(String index, IndexQuery query, CancellationToken token) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1312
   at Raven.Client.Embedded.EmbeddedDatabaseCommands.Query(String index, IndexQuery query, String[] includes, Boolean metadataOnly, Boolean indexEntriesOnly) in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Embedded\EmbeddedDatabaseCommands.cs:line 486
   at Raven.Client.Document.AbstractDocumentQuery`2.ExecuteActualQuery() in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Lightweight\Document\AbstractDocumentQuery.cs:line 680
   at Raven.Client.Document.AbstractDocumentQuery`2.get_QueryResult() in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Lightweight\Document\AbstractDocumentQuery.cs:line 650
   at ServiceControl.MessageFailures.Api.GetAllErrors.<.ctor>b__0_0(Object _) in C:\Build\src\ServiceControl\MessageFailures\Api\GetAllErrors.cs:line 20
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
2016-10-05 19:35:36.8490|61|Error|ServiceBus.Management.Infrastructure.Nancy.NServiceBusContainerBootstrapper|Http call failed
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Raven.Database.DocumentDatabase.<>c__DisplayClass97.<Query>b__8c(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1404
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 712
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 656
   at Raven.Database.DocumentDatabase.Query(String index, IndexQuery query, CancellationToken externalCancellationToken, Action`1 headerInfo, Action`1 onResult) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1416
   at Raven.Database.DocumentDatabase.Query(String index, IndexQuery query, CancellationToken token) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1312
   at Raven.Client.Embedded.EmbeddedDatabaseCommands.Query(String index, IndexQuery query, String[] includes, Boolean metadataOnly, Boolean indexEntriesOnly) in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Embedded\EmbeddedDatabaseCommands.cs:line 486
   at Raven.Client.Document.AbstractDocumentQuery`2.ExecuteActualQuery() in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Lightweight\Document\AbstractDocumentQuery.cs:line 680
   at Raven.Client.Document.AbstractDocumentQuery`2.get_QueryResult() in c:\Builds\RavenDB-Stable-2.5\Raven.Client.Lightweight\Document\AbstractDocumentQuery.cs:line 650
   at ServiceControl.MessageFailures.Api.GetAllErrors.<.ctor>b__0_0(Object _) in C:\Build\src\ServiceControl\MessageFailures\Api\GetAllErrors.cs:line 20
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

```

```
-------------------------------------------------------------
ServiceControl Version:				1.23.0.0
Selected Transport:					NServiceBus.SqlServerTransport, NServiceBus.Transports.SQLServer
Audit Retention Period:				30.00:00:00
Error Retention Period:				15.00:00:00
Forwarding Error Messages:		False
Forwarding Audit Messages:		False
Database Size:							16879591424bytes
-------------------------------------------------------------
2016-10-05 13:15:07.5338|5|Warn|Raven.Database.Indexing.IndexStorage.Startup|Unclean shutdown detected on SagaDetailsIndex, checking the index for errors. This may take a while.
2016-10-05 13:16:01.4179|5|Warn|Raven.Database.Indexing.IndexStorage.Startup|Checking index SagaDetailsIndex took: 00:00:53.8619461, clean: True
2016-10-05 13:16:01.4179|5|Warn|Raven.Database.Indexing.IndexStorage|Segments file=segments_1of numSegments=5 version=FORMAT_DIAGNOSTICS [Lucene 2.9] userData={Marker=1894770433366671683}
  1 of 5: name=_28a docCount=128
    compound=False
    hasProx=True
    numFiles=8
    size (MB)=866.30
    diagnostics = {os=Windows_NT, mergeDocStores=True, optimize=False, lucene.version=3.0.3.0, mergeFactor=10, source=merge, os.arch=AMD64, java.version=, os.version=Microsoft Windows NT 6.1.7601 Service Pack 1, java.vendor=}
    has deletions [delFileName=_28a_1.del]
    test: open reader.........OK [1 deleted docs]
    test: fields..............OK [8 fields]
    test: field norms.........OK [0 fields]
    test: terms, freq, prox...OK [384064 terms; 384442 terms/docs pairs; 2303 tokens]
    test: stored fields.......OK [961 total field count; avg 7.57 fields per doc]
    test: term vectors........OK [0 total vector count; avg 0.00 term/freq vector fields per doc]

  2 of 5: name=_28l docCount=23
    compound=True
    hasProx=True
    numFiles=1
    size (MB)=0.63
    diagnostics = {os=Windows_NT, mergeDocStores=True, optimize=False, lucene.version=3.0.3.0, mergeFactor=10, source=merge, os.arch=AMD64, java.version=, os.version=Microsoft Windows NT 6.1.7601 Service Pack 1, java.vendor=}
    no deletions
    test: open reader.........OK
    test: fields..............OK [8 fields]
    test: field norms.........OK [0 fields]
    test: terms, freq, prox...OK [302 terms; 367 terms/docs pairs; 573 tokens]
    test: stored fields.......OK [252 total field count; avg 10.96 fields per doc]
    test: term vectors........OK [0 total vector count; avg 0.00 term/freq vector fields per doc]

  3 of 5: name=_28m docCount=3
    compound=True
    hasProx=True
    numFiles=1
    size (MB)=0.05
    diagnostics = {os=Windows_NT, lucene.version=3.0.3.0, source=flush, os.arch=AMD64, java.version=, os.version=Microsoft Windows NT 6.1.7601 Service Pack 1, java.vendor=}
    no deletions
    test: open reader.........OK
    test: fields..............OK [8 fields]
    test: field norms.........OK [0 fields]
    test: terms, freq, prox...OK [30 terms; 34 terms/docs pairs; 47 tokens]
    test: stored fields.......OK [19 total field count; avg 6.33 fields per doc]
    test: term vectors........OK [0 total vector count; avg 0.00 term/freq vector fields per doc]

  4 of 5: name=_28n docCount=12
    compound=True
    hasProx=True
    numFiles=2
    size (MB)=0.22
    diagnostics = {os=Windows_NT, lucene.version=3.0.3.0, source=flush, os.arch=AMD64, java.version=, os.version=Microsoft Windows NT 6.1.7601 Service Pack 1, java.vendor=}
    has deletions [delFileName=_28n_1.del]
    test: open reader.........OK [8 deleted docs]
    test: fields..............OK [8 fields]
    test: field norms.........OK [0 fields]
    test: terms, freq, prox...OK [119 terms; 150 terms/docs pairs; 72 tokens]
    test: stored fields.......OK [30 total field count; avg 7.50 fields per doc]
    test: term vectors........OK [0 total vector count; avg 0.00 term/freq vector fields per doc]

  5 of 5: n
2016-10-05 14:40:54.4196|32|Warn|Raven.Database.Prefetching.PrefetchingBehavior|WASTE: Discarding future work item without using it, to reduce memory usage

```

**Comment by johnsimons** [comment]
Hi @kye,

Can you please contact us via http://particular.net/support, so we handle this in a more secure private way

**Comment by kye** [comment]
Yep - I've submitted a form. Please let me know whether there is a cost involved and I will seek management approval. Thank you.

**Comment by johnsimons** [comment]
Closing as being handled by our support
