### ISSUE TITLE
ServiceControl crashes because of TimeoutException

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#878]
### Symptoms

ServiceControl process is killed due to an unhandled exception in the transport (RabbitMQ)

### Affected users

Users who run ServiceControl on broker transports that can experience connectivity problems (MSMQ, RabbitMQ, ASB, ASQ)

### Root cause

The `ServiceControl.HeartbeatMonitoring.HeartbeatsMonitor+HeartbeatMonitor.UpdateStatuses()` method sends messages without proper defensive code which causes the exception to be escalated to the timer and effectively kill the application.

### Logs

```
Application: ServiceControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TimeoutException
   at RabbitMQ.Util.BlockingCell.GetValue(System.TimeSpan)
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(System.TimeSpan)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(RabbitMQ.Client.Impl.MethodBase, RabbitMQ.Client.Impl.ContentHeaderBase, Byte[])
   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(System.String)
   at RabbitMQ.Client.Framing.Impl.Connection.CreateModel()
   at NServiceBus.Transports.RabbitMQ.ConfirmsAwareChannel..ctor(RabbitMQ.Client.IConnection, Boolean, System.TimeSpan)
   at NServiceBus.Transports.RabbitMQ.ChannelProvider.GetNewPublishChannel()
   at NServiceBus.Transports.RabbitMQ.RabbitMqMessageSender.Send(NServiceBus.TransportMessage, NServiceBus.Unicast.SendOptions)
   at NServiceBus.DispatchMessageToTransportBehavior.SendOrDefer(NServiceBus.TransportMessage, NServiceBus.Unicast.SendOptions)
   at NServiceBus.DispatchMessageToTransportBehavior.InvokeNative(NServiceBus.Unicast.DeliveryOptions, NServiceBus.TransportMessage)
   at NServiceBus.DispatchMessageToTransportBehavior.Invoke(NServiceBus.Pipeline.Contexts.OutgoingContext, System.Action)
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.SerializeMessagesBehavior.Invoke(NServiceBus.Pipeline.Contexts.OutgoingContext, System.Action)
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.CreatePhysicalMessageBehavior.Invoke(NServiceBus.Pipeline.Contexts.OutgoingContext, System.Action)
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.PopulateAutoCorrelationHeadersForRepliesBehavior.Invoke(NServiceBus.Pipeline.Contexts.OutgoingContext, System.Action)
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeNext(System.__Canon)
   at NServiceBus.BehaviorChain`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke()
   at NServiceBus.Pipeline.PipelineExecutor.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](NServiceBus.BehaviorChain`1<System.__Canon>, System.__Canon)
   at NServiceBus.Pipeline.PipelineExecutor.InvokeSendPipeline(NServiceBus.Unicast.DeliveryOptions, NServiceBus.Unicast.Messages.LogicalMessage)
   at NServiceBus.Unicast.UnicastBus.SendMessage(NServiceBus.Unicast.SendOptions, NServiceBus.Unicast.Messages.LogicalMessage)
   at ServiceControl.HeartbeatMonitoring.HeartbeatsMonitor+HeartbeatMonitor.UpdateStatuses()
   at ServiceControl.HeartbeatMonitoring.HeartbeatsMonitor+HeartbeatMonitor.Refresh(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by dsosunov** [comment]
[logfile.2016-12-20.zip](https://github.com/Particular/ServiceControl/files/663468/logfile.2016-12-20.zip)

Attached log from ServiceControl

**Comment by SzymonPobiega** [comment]
Thanks @dsosunov . Which version of NServiceBus.RabbitMQTransport are you using?

**Comment by dsosunov** [comment]
[ravenlog.2016-12-20.zip](https://github.com/Particular/ServiceControl/files/663481/ravenlog.2016-12-20.zip)

RavenDB logs

**Comment by dsosunov** [comment]
RabbitMQ 3.6.2, Erlang 18.3

**Comment by SzymonPobiega** [comment]
@dsosunov thank you very much. We're on that. It seems like there are connectivity problems with rabbit and they are not handled correctly in certain places. The log entry

```
2016-12-20 01:58:25.0720|5|Fatal|NServiceBus|Startup task failed to complete.
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
```

is an example where SC seems to handle it correctly but the `at ServiceControl.HeartbeatMonitoring.HeartbeatsMonitor+HeartbeatMonitor.UpdateStatuses()` seems to not have appropriate code around the transport invocation.

**Comment by dsosunov** [comment]
Any workaround?

**Comment by SzymonPobiega** [comment]
@dsosunov I think the initial cause here is the unavailability of RabbitMQ broker. The timeouts should not happen during normal operations. We will make sure that a proper circuit breaker mechanism is in place in the offending code but from ServiceControl perspective there is not much we can do if we experience repeating errors from the transport infrastructure (RabbitMQ). All we can do is kill the endpoint so that the Windows service manager restarts and hope the RabbitMQ issue is resolved in the meantime.

**Comment by dsosunov** [comment]
I have got a new issue. While SC is down heartbeats continue sending into the queue. Queue is growing.
When I'am trying to start SC:

Service cannot be started. System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Unicast.UnicastBus.Start() in C:\Build\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 668
   at Particular.ServiceControl.Bootstrapper.Start(Boolean isRunningAcceptanceTests) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Bootstrapper.cs:line 90
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**Comment by dsosunov** [comment]
If delete Raven DB and restart SC the issue can be temporary resolved.

**Comment by SzymonPobiega** [comment]
@dsosunov is the timeout problem solved too?

**Comment by dsosunov** [comment]
Yes, 
our development environment has three RabbitMQ nodes with NGINX as load balancer. So, timeouts is not a result of our RabbitMQ cluster. It was available when we have discovered the issue.
