### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'TimeKeeper'.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#950]
Getting the following error which seems to happen during a shutdown at start.

# Exception

>NServiceBus.Unicast.UnicastBus|Startup task failed to stop.
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'TimeKeeper'.

# Stacktrace
```
2017-04-06 15:54:15.5244|45|Fatal|NServiceBus.Unicast.UnicastBus|Startup task failed to stop.
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'TimeKeeper'.
   at ServiceControl.Infrastructure.TimeKeeper.ThrowIfDisposed() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\TimeKeeper.cs:line 98
   at ServiceControl.Infrastructure.TimeKeeper.Release(Timer timer) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\TimeKeeper.cs:line 66
   at ServiceControl.Recoverability.FailedMessageRetries.BulkRetryBatchCreation.OnStop() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retrying\FailedMessageRetries.cs:line 59
   at NServiceBus.Features.FeatureActivator.StopFeatures(IBuilder builder) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 152
   at NServiceBus.Unicast.UnicastBus.<>c.<ExecuteIWantToRunAtStartupStopMethods>b__93_0(IWantToRunWhenBusStartsAndStops toRun) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 711
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NServiceBus.Unicast.UnicastBus.<>c__DisplayClass133_0`1.<ProcessStartupItems>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 927
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'TimeKeeper'.
   at ServiceControl.Infrastructure.TimeKeeper.ThrowIfDisposed() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\TimeKeeper.cs:line 98
   at ServiceControl.Infrastructure.TimeKeeper.Release(Timer timer) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\TimeKeeper.cs:line 66
   at ServiceControl.Recoverability.FailedMessageRetries.BulkRetryBatchCreation.OnStop() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retrying\FailedMessageRetries.cs:line 59
   at NServiceBus.Features.FeatureActivator.StopFeatures(IBuilder builder) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 152
   at NServiceBus.Unicast.UnicastBus.<>c.<ExecuteIWantToRunAtStartupStopMethods>b__93_0(IWantToRunWhenBusStartsAndStops toRun) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 711
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NServiceBus.Unicast.UnicastBus.<>c__DisplayClass133_0`1.<ProcessStartupItems>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 927
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'TimeKeeper'.
   at ServiceControl.Infrastructure.TimeKeeper.ThrowIfDisposed() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\TimeKeeper.cs:line 98
   at ServiceControl.Infrastructure.TimeKeeper.Release(Timer timer) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Infrastructure\TimeKeeper.cs:line 66
   at ServiceControl.Recoverability.FailedMessageRetries.BulkRetryBatchCreation.OnStop() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retrying\FailedMessageRetries.cs:line 59
   at NServiceBus.Features.FeatureActivator.StopFeatures(IBuilder builder) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 152
   at NServiceBus.Unicast.UnicastBus.<>c.<ExecuteIWantToRunAtStartupStopMethods>b__93_0(IWantToRunWhenBusStartsAndStops toRun) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 711
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---


```

**Comment by SzymonPobiega** [comment]
`TimeKeeper` has been replaced with `AsyncTimer` so closing this one.
