### ISSUE TITLE
ServiceControl crashes when importing messages that share the same NServiceBus message ID

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#952]
If there are lots of messages in the audit queue that share the same message ID then ServiceControl crashes as the circuit breaker is activated.

>2017-04-12 09:35:25.4287|7|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
>2017-04-12 09:35:25.4287|17|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
>2017-04-12 09:35:25.4443|6|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
>2017-04-12 09:35:25.4603|20|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock

This results in ingestion of message to come to a halt.

```
2017-04-12 09:35:25.4287|7|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2739
   at Microsoft.Isam.Esent.Interop.Api.JetPrepareUpdate(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2353
   at Microsoft.Isam.Esent.Interop.Update..ctor(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Update.cs:line 51
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.AddAttachment(String key, Etag etag, Stream data, RavenJObject headers) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\DocumentStorageActions.cs:line 53
   at Raven.Database.DocumentDatabase.<>c__DisplayClassd4.<PutStatic>b__cb(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1750
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 712
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 656
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 679
   at Raven.Database.DocumentDatabase.PutStatic(String name, Etag etag, Stream data, RavenJObject metadata) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1744
   at ServiceControl.Operations.BodyStorage.RavenAttachments.RavenAttachmentsBodyStorage.Store(String bodyId, String contentType, Int32 bodySize, Stream bodyStream) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\RavenAttachments\RavenAttachmentsBodyStorage.cs:line 19
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreBodyInBodyStorage(Byte[] body, String bodyId, String contentType, Int32 bodySize) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 109
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.TryStoreBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Int32 bodySize, String contentType, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 91
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreMessageBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 61
   at ServiceControl.Operations.AuditQueueImport.ConvertToSaveMessage(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 121
   at ServiceControl.Operations.AuditQueueImport.InnerHandle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 93
   at ServiceControl.Operations.AuditQueueImport.Handle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 52
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 89
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 344
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action(TransactionSettings transactionSettings, TransactionOptions transactionOptions, MsmqUnitOfWork unitOfWork, MessageQueue receiveQueue, MessageQueue errorQueue, CircuitBreaker circuitBreaker, CriticalError criticalError, AutoResetEvent peekResetEvent, TimeSpan receiveTimeout, SemaphoreSlim throttlingSemaphore, Func`2 tryProcessMessage, Action`2 endProcessMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 229
2017-04-12 09:35:25.4287|17|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2739
   at Microsoft.Isam.Esent.Interop.Api.JetPrepareUpdate(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2353
   at Microsoft.Isam.Esent.Interop.Update..ctor(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Update.cs:line 51
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.AddAttachment(String key, Etag etag, Stream data, RavenJObject headers) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\DocumentStorageActions.cs:line 53
   at Raven.Database.DocumentDatabase.<>c__DisplayClassd4.<PutStatic>b__cb(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1750
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 712
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 656
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 679
   at Raven.Database.DocumentDatabase.PutStatic(String name, Etag etag, Stream data, RavenJObject metadata) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1744
   at ServiceControl.Operations.BodyStorage.RavenAttachments.RavenAttachmentsBodyStorage.Store(String bodyId, String contentType, Int32 bodySize, Stream bodyStream) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\RavenAttachments\RavenAttachmentsBodyStorage.cs:line 19
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreBodyInBodyStorage(Byte[] body, String bodyId, String contentType, Int32 bodySize) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 109
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.TryStoreBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Int32 bodySize, String contentType, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 91
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreMessageBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 61
   at ServiceControl.Operations.AuditQueueImport.ConvertToSaveMessage(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 121
   at ServiceControl.Operations.AuditQueueImport.InnerHandle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 93
   at ServiceControl.Operations.AuditQueueImport.Handle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 52
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 89
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 344
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action(TransactionSettings transactionSettings, TransactionOptions transactionOptions, MsmqUnitOfWork unitOfWork, MessageQueue receiveQueue, MessageQueue errorQueue, CircuitBreaker circuitBreaker, CriticalError criticalError, AutoResetEvent peekResetEvent, TimeSpan receiveTimeout, SemaphoreSlim throttlingSemaphore, Func`2 tryProcessMessage, Action`2 endProcessMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 229
2017-04-12 09:35:25.4443|6|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2739
   at Microsoft.Isam.Esent.Interop.Api.JetPrepareUpdate(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2353
   at Microsoft.Isam.Esent.Interop.Update..ctor(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Update.cs:line 51
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.AddAttachment(String key, Etag etag, Stream data, RavenJObject headers) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\DocumentStorageActions.cs:line 53
   at Raven.Database.DocumentDatabase.<>c__DisplayClassd4.<PutStatic>b__cb(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1750
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 712
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 656
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 679
   at Raven.Database.DocumentDatabase.PutStatic(String name, Etag etag, Stream data, RavenJObject metadata) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1744
   at ServiceControl.Operations.BodyStorage.RavenAttachments.RavenAttachmentsBodyStorage.Store(String bodyId, String contentType, Int32 bodySize, Stream bodyStream) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\RavenAttachments\RavenAttachmentsBodyStorage.cs:line 19
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreBodyInBodyStorage(Byte[] body, String bodyId, String contentType, Int32 bodySize) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 109
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.TryStoreBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Int32 bodySize, String contentType, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 91
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreMessageBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 61
   at ServiceControl.Operations.AuditQueueImport.ConvertToSaveMessage(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 121
   at ServiceControl.Operations.AuditQueueImport.InnerHandle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 93
   at ServiceControl.Operations.AuditQueueImport.Handle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 52
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 89
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 344
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action(TransactionSettings transactionSettings, TransactionOptions transactionOptions, MsmqUnitOfWork unitOfWork, MessageQueue receiveQueue, MessageQueue errorQueue, CircuitBreaker circuitBreaker, CriticalError criticalError, AutoResetEvent peekResetEvent, TimeSpan receiveTimeout, SemaphoreSlim throttlingSemaphore, Func`2 tryProcessMessage, Action`2 endProcessMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 229
2017-04-12 09:35:25.4603|20|Fatal|NServiceBus|Failed to import too many times
Raven.Abstractions.Exceptions.ConcurrencyException: Concurrent modification to the same document are not allowed ---> Microsoft.Isam.Esent.Interop.EsentWriteConflictException: Write lock failed due to outstanding write lock
   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2739
   at Microsoft.Isam.Esent.Interop.Api.JetPrepareUpdate(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2353
   at Microsoft.Isam.Esent.Interop.Update..ctor(JET_SESID sesid, JET_TABLEID tableid, JET_prep prep) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Update.cs:line 51
   at Raven.Storage.Esent.StorageActions.DocumentStorageActions.AddAttachment(String key, Etag etag, Stream data, RavenJObject headers) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\StorageActions\DocumentStorageActions.cs:line 53
   at Raven.Database.DocumentDatabase.<>c__DisplayClassd4.<PutStatic>b__cb(IStorageActionsAccessor actions) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1750
   at Raven.Storage.Esent.TransactionalStorage.ExecuteBatch(Action`1 action, EsentTransactionContext transactionContext) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 712
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 656
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Batch(Action`1 action) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\Storage\Esent\TransactionalStorage.cs:line 679
   at Raven.Database.DocumentDatabase.PutStatic(String name, Etag etag, Stream data, RavenJObject metadata) in c:\Builds\RavenDB-Stable-2.5\Raven.Database\DocumentDatabase.cs:line 1744
   at ServiceControl.Operations.BodyStorage.RavenAttachments.RavenAttachmentsBodyStorage.Store(String bodyId, String contentType, Int32 bodySize, Stream bodyStream) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\RavenAttachments\RavenAttachmentsBodyStorage.cs:line 19
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreBodyInBodyStorage(Byte[] body, String bodyId, String contentType, Int32 bodySize) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 109
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.TryStoreBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Int32 bodySize, String contentType, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 91
   at ServiceControl.Operations.BodyStorage.BodyStorageFeature.BodyStorageEnricher.StoreMessageBody(Byte[] body, IReadOnlyDictionary`2 headers, IDictionary`2 metadata, Boolean isFailedMessage) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\BodyStorage\BodyStorageFeature.cs:line 61
   at ServiceControl.Operations.AuditQueueImport.ConvertToSaveMessage(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 121
   at ServiceControl.Operations.AuditQueueImport.InnerHandle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 93
   at ServiceControl.Operations.AuditQueueImport.Handle(TransportMessage message) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Operations\AuditQueueImport.cs:line 52
   at NServiceBus.Satellites.SatelliteLauncher.HandleMessageReceived(Object sender, TransportMessageReceivedEventArgs e, ISatellite satellite) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Satellites\SatelliteLauncher.cs:line 89
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 344
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action(TransactionSettings transactionSettings, TransactionOptions transactionOptions, MsmqUnitOfWork unitOfWork, MessageQueue receiveQueue, MessageQueue errorQueue, CircuitBreaker circuitBreaker, CriticalError criticalError, AutoResetEvent peekResetEvent, TimeSpan receiveTimeout, SemaphoreSlim throttlingSemaphore, Func`2 tryProcessMessage, Action`2 endProcessMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 229
```

**Comment by mikeminutillo** [comment]
It's not just MessageId. SC derives a value called `UniqueMessageId` which is based on the Message Id and the Processing Endpoint. All records with the same `UniqueMessageId` are stored in the same Raven document so if SC is trying to import 30 of these at the same time it is going to get 29 concurrency exceptions and one success.

It is not designed to handle this situation. Why do you have many messages with the same Id?

**Comment by ramonsmits** [comment]
@mikeminutillo This is based on a case where this happened due to https://github.com/Particular/NServiceBus/issues/4613 . This was unnoticed until the messages were ingested by SC.

It should not result in SC to fail and should also not result in the 'duplicates'  to be discarded as they aren't actually duplicates.

For example, imagine a FTP drop of a CSV, each row is send as a message with shared sendoptions which would just be happily processed by the endpoint but SC suddenly does not ingest them any more.

**Comment by SzymonPobiega** [comment]
@mikeminutillo @ramonsmits I think we should try to detect that case and then move the offending messages straight to the `error.log` or failed imports. We can't support having non-unique message ids because this will just invalidate most of the logic in SC.

**Comment by WilliamBZA** [comment]
This also manifests as extremely poor import performance too as the same failed message document eventually becomes very large and serializing and deserializing the message takes a while.

**Comment by SzymonPobiega** [comment]
This issue has been fixed by adding a workaround (a lock in our code to protect RavenDB) and then it has also been fixed on RavenDB side as well so in the latest version the workaround has been removed.
