### ISSUE TITLE
Exception logged when Forwarding Retries and Shutting Down 

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl#969]
When a ServiceControl instance is Forwarding Retry messages and it is shut down you see this in the logs:

```
2017-06-01 10:33:57.6739|17|Error|ServiceControl.Recoverability.FailedMessageRetries+ProcessRetryBatches|Error during retry batch processing
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ServiceControl.Recoverability.ReturnToSenderDequeuer.Run(Predicate`1 filter, CancellationToken cancellationToken, Nullable`1 expectedMessageCount) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retrying\Infrastructure\ReturnToSenderDequeuer.cs:line 168
   at ServiceControl.Recoverability.RetryProcessor.Forward(RetryBatch forwardingBatch, IDocumentSession session, CancellationToken cancellationToken) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retrying\RetryProcessor.cs:line 111
   at ServiceControl.Recoverability.RetryProcessor.ForwardCurrentBatch(IDocumentSession session, CancellationToken cancellationToken) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retrying\RetryProcessor.cs:line 89
   at ServiceControl.Recoverability.FailedMessageRetries.ProcessRetryBatches.Process() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl\Recoverability\Retrying\FailedMessageRetries.cs:line 169
```

The shutdown is indicated by a CancellationToken that is created and managed by the Retries Startup feature [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Retrying/FailedMessageRetries.cs#L171)

When it gets cancelled, the code that is forwarding messages throws an exception [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Retrying/Infrastructure/ReturnToSenderDequeuer.cs#L167). NOTE that we check if the cancellation token is cancelled below but the implementation of the reset event throws when the token is cancelled. 

The startup feature that manages the timer for processing batches catches and logs that error [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Retrying/FailedMessageRetries.cs#L178) even though it is expected. 

This is annoying but ignorable. The SC instance is shutting down in a clean state and when it's restarted it will recover just fine.

**Comment by SzymonPobiega** [comment]
`ReturnToSenderDequeuer` has been since rewritten to use NServiceBus.Raw so there is a fair chance this does not happen any more.

**Comment by kbaley** [comment]
Triaging with @boblangley. Given the age, the fact it's been rewritten, and the fact that this is an annoyance and hasn't been reported in the wild, we're going to close. It can be re-opened if it comes up again.
