### ISSUE TITLE
Feedback: When storage disk is full write a helpful message to the log

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#983]
When the disk is full the following message gets written to the log:
```
Service cannot be started. System.InvalidOperationException: Could not open transactional storage: C:\ProgramData\Particular\ServiceControl\Newton_OTD_DevTest.ServiceControl\DB\Data ---> System.InvalidOperationException: Could not read db details from disk. It is likely that there is a version difference between the library and the db on the disk.
You need to migrate the disk version to the library version, alternatively, if the data isn't important, you can delete the file and it will be re-created (with no data) with the library version. ---> Microsoft.Isam.Esent.Interop.EsentInstanceUnavailableException: This instance cannot be used because it encountered a fatal error
   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2739
   at Microsoft.Isam.Esent.Interop.Api.JetEndSession(JET_SESID sesid, EndSessionGrbit grbit) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 857
   at Microsoft.Isam.Esent.Interop.Sessio...
```

The cause was that the storage disk was full. Please see if you could improve the written log issue

## Proposal

- At start log the available disk space by querying WMI or using performance counters and write a warning if disk is near empty.
- Catch this exception, wrap it in a new exception that mentioned that a cause could be that the storage disk is full.

**Comment by danielmarbach** [comment]
Just had a case over gitter where a user ran into this. Interestingly when the disk is almost full the exception starts then filling the logs. Due to https://github.com/NLog/NLog/issues/1190 the log files grow and grow thus contributing to eating up the disk space.
